/* GymLog — seed data: muscle groups, equipment, exercise library, i18n */

const MUSCLES = [
  { id: 'chest',      en: 'Chest',      ru: 'Грудь' },
  { id: 'back',       en: 'Back',       ru: 'Спина' },
  { id: 'shoulders',  en: 'Shoulders',  ru: 'Плечи' },
  { id: 'biceps',     en: 'Biceps',     ru: 'Бицепс' },
  { id: 'triceps',    en: 'Triceps',    ru: 'Трицепс' },
  { id: 'forearms',   en: 'Forearms',   ru: 'Предплечья' },
  { id: 'quads',      en: 'Quads',      ru: 'Квадрицепс' },
  { id: 'hamstrings', en: 'Hamstrings', ru: 'Бицепс бедра' },
  { id: 'glutes',     en: 'Glutes',     ru: 'Ягодицы' },
  { id: 'calves',     en: 'Calves',     ru: 'Икры' },
  { id: 'core',       en: 'Core',       ru: 'Кор / Пресс' },
  { id: 'cardio',     en: 'Cardio',     ru: 'Кардио' },
];

const EQUIPMENT = [
  { id: 'barbell',    en: 'Barbell',    ru: 'Штанга' },
  { id: 'dumbbell',   en: 'Dumbbell',   ru: 'Гантели' },
  { id: 'machine',    en: 'Machine',    ru: 'Тренажёр' },
  { id: 'cable',      en: 'Cable',      ru: 'Блок' },
  { id: 'bodyweight', en: 'Bodyweight', ru: 'Свой вес' },
  { id: 'other',      en: 'Other',      ru: 'Другое' },
];

// kind: 'wr' = weight x reps | 'reps' = reps only (weight optional) | 'time' = duration
// warn: 'back' | 'shoulder'  -> flagged against Artem's program constraints
const SEED_EXERCISES = [
  // ---- Chest ----
  { id: 'bb-bench',        en: 'Barbell Bench Press',       ru: 'Жим штанги лёжа',                m: 'chest', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['bench', 'bp', 'жим лежа'] },
  { id: 'bb-incline',      en: 'Incline Barbell Press',     ru: 'Жим штанги на наклонной',        m: 'chest', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['incline bench', 'bench'] },
  { id: 'db-bench',        en: 'Dumbbell Bench Press',      ru: 'Жим гантелей лёжа',              m: 'chest', eq: 'dumbbell',   kind: 'wr', alias: ['bench', 'db bench'] },
  { id: 'db-incline',      en: 'Incline Dumbbell Press',    ru: 'Жим гантелей на наклонной',      m: 'chest', eq: 'dumbbell',   kind: 'wr', alias: ['incline', 'db incline', 'bench'] },
  { id: 'machine-press',   en: 'Machine Chest Press',       ru: 'Жим в тренажёре',                m: 'chest', eq: 'machine',    kind: 'wr', alias: ['chest press'] },
  { id: 'pec-deck',        en: 'Pec Deck / Machine Fly',    ru: 'Сведения в тренажёре («бабочка»)', m: 'chest', eq: 'machine',  kind: 'wr', alias: ['fly', 'butterfly', 'бабочка'] },
  { id: 'cable-fly',       en: 'Cable Fly',                 ru: 'Сведения в кроссовере',          m: 'chest', eq: 'cable',      kind: 'wr', alias: ['fly', 'crossover', 'кроссовер'] },
  { id: 'push-up',         en: 'Push-Up',                   ru: 'Отжимания от пола',              m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['pushup', 'отжимания'] },
  { id: 'chest-dip',       en: 'Chest Dip',                 ru: 'Отжимания на брусьях (грудь)',   m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['dips', 'брусья'] },

  // ---- Back ----
  { id: 'lat-pulldown',    en: 'Lat Pulldown',              ru: 'Тяга верхнего блока',            m: 'back', eq: 'machine',    kind: 'wr', alias: ['pulldown', 'lpd', 'тяга блока'] },
  { id: 'pull-up',         en: 'Pull-Up',                   ru: 'Подтягивания',                   m: 'back', eq: 'bodyweight', kind: 'reps', alias: ['pullup', 'chin-up', 'chinup', 'турник'] },
  { id: 'assisted-pullup', en: 'Assisted Pull-Up',          ru: 'Подтягивания в гравитроне',      m: 'back', eq: 'machine',    kind: 'wr', alias: ['gravitron', 'гравитрон', 'pullup'] },
  { id: 'seated-row',      en: 'Seated Cable Row',          ru: 'Тяга нижнего блока сидя',        m: 'back', eq: 'cable',      kind: 'wr', alias: ['row', 'cable row', 'low row'] },
  { id: 'cs-row',          en: 'Chest-Supported Row',       ru: 'Тяга с упором в грудь',          m: 'back', eq: 'machine',    kind: 'wr', alias: ['row', 'seal row'] },
  { id: 'bb-row',          en: 'Barbell Row',               ru: 'Тяга штанги в наклоне',          m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['row', 'bent over row', 'bor'] },
  { id: 'db-row',          en: 'One-Arm Dumbbell Row',      ru: 'Тяга гантели в наклоне',         m: 'back', eq: 'dumbbell',   kind: 'wr', alias: ['row', 'db row'] },
  { id: 't-bar-row',       en: 'T-Bar Row',                 ru: 'Т-тяга',                         m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['row', 't bar', 'tbar'] },
  { id: 'sa-pulldown',     en: 'Straight-Arm Pulldown',     ru: 'Пуловер на верхнем блоке',       m: 'back', eq: 'cable',      kind: 'wr', alias: ['pulldown', 'pullover', 'пуловер'] },
  { id: 'deadlift',        en: 'Conventional Deadlift',     ru: 'Становая тяга',                  m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['dl', 'deadlift', 'становая'] },
  { id: 'rack-pull',       en: 'Rack Pull',                 ru: 'Тяга с плинтов',                 m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['dl', 'rack pull'] },
  { id: 'db-shrug',        en: 'Dumbbell Shrug',            ru: 'Шраги с гантелями',              m: 'back', eq: 'dumbbell',   kind: 'wr', alias: ['shrug', 'шраги'] },

  // ---- Shoulders ----
  { id: 'db-shoulder',     en: 'Dumbbell Shoulder Press',   ru: 'Жим гантелей сидя',              m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['ohp', 'shoulder press', 'db ohp'] },
  { id: 'bb-ohp',          en: 'Barbell Overhead Press',    ru: 'Жим штанги стоя',                m: 'shoulders', eq: 'barbell',  kind: 'wr', warn: 'shoulder', alias: ['ohp', 'military press', 'overhead press', 'армейский жим'] },
  { id: 'machine-shoulder',en: 'Machine Shoulder Press',    ru: 'Жим в тренажёре сидя',           m: 'shoulders', eq: 'machine',  kind: 'wr', alias: ['shoulder press', 'ohp'] },
  { id: 'lateral-raise',   en: 'Lateral Raise',             ru: 'Махи гантелями в стороны',       m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['lat raise', 'side raise', 'махи'] },
  { id: 'cable-lateral',   en: 'Cable Lateral Raise',       ru: 'Махи в стороны на блоке',        m: 'shoulders', eq: 'cable',    kind: 'wr', alias: ['lat raise', 'side raise'] },
  { id: 'rear-delt-fly',   en: 'Rear Delt Fly',             ru: 'Махи в наклоне (задняя дельта)', m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['reverse fly', 'rear delt'] },
  { id: 'face-pull',       en: 'Face Pull',                 ru: 'Тяга к лицу',                    m: 'shoulders', eq: 'cable',    kind: 'wr', alias: ['facepull'] },
  { id: 'front-raise',     en: 'Front Raise',               ru: 'Подъём гантелей перед собой',    m: 'shoulders', eq: 'dumbbell', kind: 'wr' },
  { id: 'upright-row',     en: 'Upright Row',               ru: 'Тяга к подбородку',              m: 'shoulders', eq: 'barbell',  kind: 'wr', warn: 'shoulder' },

  // ---- Biceps ----
  { id: 'bb-curl',         en: 'Barbell Curl',              ru: 'Подъём штанги на бицепс',        m: 'biceps', eq: 'barbell',  kind: 'wr', alias: ['curl', 'bicep curl'] },
  { id: 'db-curl',         en: 'Dumbbell Curl',             ru: 'Подъём гантелей на бицепс',      m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'bicep curl'] },
  { id: 'hammer-curl',     en: 'Hammer Curl',               ru: 'Молотковые сгибания',            m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'молотки'] },
  { id: 'incline-curl',    en: 'Incline Dumbbell Curl',     ru: 'Сгибания на наклонной скамье',   m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl'] },
  { id: 'preacher-curl',   en: 'Preacher Curl',             ru: 'Сгибания на скамье Скотта',      m: 'biceps', eq: 'machine',  kind: 'wr', alias: ['curl', 'скотт'] },
  { id: 'cable-curl',      en: 'Cable Curl',                ru: 'Сгибания на нижнем блоке',       m: 'biceps', eq: 'cable',    kind: 'wr', alias: ['curl'] },

  // ---- Triceps ----
  { id: 'pushdown',        en: 'Triceps Pushdown',          ru: 'Разгибания на блоке',            m: 'triceps', eq: 'cable',      kind: 'wr', alias: ['tricep pushdown', 'pressdown'] },
  { id: 'rope-pushdown',   en: 'Rope Pushdown',             ru: 'Разгибания с канатом',           m: 'triceps', eq: 'cable',      kind: 'wr', alias: ['tricep pushdown', 'pressdown', 'rope'] },
  { id: 'oh-triceps',      en: 'Overhead Triceps Extension',ru: 'Французский жим стоя',           m: 'triceps', eq: 'dumbbell',   kind: 'wr', alias: ['french press', 'overhead extension', 'французский'] },
  { id: 'skullcrusher',    en: 'Skullcrusher',              ru: 'Французский жим лёжа',           m: 'triceps', eq: 'barbell',    kind: 'wr', alias: ['skull crusher', 'french press', 'lying extension', 'французский'] },
  { id: 'cg-bench',        en: 'Close-Grip Bench Press',    ru: 'Жим узким хватом',               m: 'triceps', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['cgbp', 'close grip', 'bench'] },
  { id: 'triceps-dip',     en: 'Triceps Dip',               ru: 'Отжимания на брусьях (трицепс)', m: 'triceps', eq: 'bodyweight', kind: 'reps', alias: ['dips', 'брусья'] },
  { id: 'bench-dip',       en: 'Bench Dip',                 ru: 'Обратные отжимания от скамьи',   m: 'triceps', eq: 'bodyweight', kind: 'reps' },

  // ---- Quads ----
  { id: 'leg-press',       en: 'Leg Press',                 ru: 'Жим ногами',                     m: 'quads', eq: 'machine',    kind: 'wr', alias: ['lp', 'жим ногами'] },
  { id: 'hack-squat',      en: 'Hack Squat',                ru: 'Гакк-приседания',                m: 'quads', eq: 'machine',    kind: 'wr', alias: ['squat', 'гакк'] },
  { id: 'machine-squat',   en: 'Machine Squat',             ru: 'Присед в тренажёре',             m: 'quads', eq: 'machine',    kind: 'wr', alias: ['squat', 'smith'] },
  { id: 'back-squat',      en: 'Barbell Back Squat',        ru: 'Присед со штангой',              m: 'quads', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['squat', 'bb squat'] },
  { id: 'front-squat',     en: 'Front Squat',               ru: 'Фронтальный присед',             m: 'quads', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['squat'] },
  { id: 'goblet-squat',    en: 'Goblet Squat',              ru: 'Гоблет-присед',                  m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['squat'] },
  { id: 'leg-extension',   en: 'Leg Extension',             ru: 'Разгибания ног сидя',            m: 'quads', eq: 'machine',    kind: 'wr', alias: ['extension', 'разгибания'] },
  { id: 'bulgarian',       en: 'Bulgarian Split Squat',     ru: 'Болгарский выпад',               m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['bss', 'split squat', 'болгарка'] },
  { id: 'lunge',           en: 'Walking Lunge',             ru: 'Выпады с гантелями',             m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['lunges'] },

  // ---- Hamstrings ----
  { id: 'lying-leg-curl',  en: 'Lying Leg Curl',            ru: 'Сгибания ног лёжа',              m: 'hamstrings', eq: 'machine',    kind: 'wr', alias: ['leg curl', 'hamstring curl'] },
  { id: 'seated-leg-curl', en: 'Seated Leg Curl',           ru: 'Сгибания ног сидя',              m: 'hamstrings', eq: 'machine',    kind: 'wr', alias: ['leg curl', 'hamstring curl'] },
  { id: 'db-rdl',          en: 'Dumbbell Romanian Deadlift',ru: 'Румынская тяга с гантелями',     m: 'hamstrings', eq: 'dumbbell',   kind: 'wr', alias: ['rdl', 'sldl', 'db rdl', 'румынка'] },
  { id: 'bb-rdl',          en: 'Barbell Romanian Deadlift', ru: 'Румынская тяга со штангой',      m: 'hamstrings', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['rdl', 'sldl', 'bb rdl', 'румынка'] },
  { id: 'good-morning',    en: 'Good Morning',              ru: 'Наклоны со штангой',             m: 'hamstrings', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['gm'] },
  { id: 'nordic-curl',     en: 'Nordic Curl',               ru: 'Нордические сгибания',           m: 'hamstrings', eq: 'bodyweight', kind: 'reps', alias: ['nordic', 'leg curl'] },

  // ---- Glutes ----
  { id: 'hip-thrust',      en: 'Barbell Hip Thrust',        ru: 'Ягодичный мост со штангой',      m: 'glutes', eq: 'barbell', kind: 'wr', alias: ['glute bridge', 'мостик'] },
  { id: 'hip-thrust-mach', en: 'Hip Thrust Machine',        ru: 'Ягодичный мост в тренажёре',     m: 'glutes', eq: 'machine', kind: 'wr', alias: ['glute bridge', 'hip thrust', 'мостик'] },
  { id: 'kickback',        en: 'Cable Glute Kickback',      ru: 'Отведение ноги назад на блоке',  m: 'glutes', eq: 'cable',   kind: 'wr', alias: ['glute kickback'] },
  { id: 'hip-abduction',   en: 'Hip Abduction Machine',     ru: 'Разведение ног в тренажёре',     m: 'glutes', eq: 'machine', kind: 'wr', alias: ['abductor', 'abduction'] },

  // ---- Calves ----
  { id: 'standing-calf',   en: 'Standing Calf Raise',       ru: 'Подъём на носки стоя',           m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },
  { id: 'seated-calf',     en: 'Seated Calf Raise',         ru: 'Подъём на носки сидя',           m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },
  { id: 'leg-press-calf',  en: 'Leg Press Calf Raise',      ru: 'Носки в жиме ногами',            m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },

  // ---- Core ----
  { id: 'plank',           en: 'Plank',                     ru: 'Планка',                         m: 'core', eq: 'bodyweight', kind: 'time' },
  { id: 'hanging-leg-raise',en:'Hanging Leg Raise',         ru: 'Подъём ног в висе',              m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['hlr', 'leg raise'] },
  { id: 'cable-crunch',    en: 'Cable Crunch',              ru: 'Скручивания на блоке',           m: 'core', eq: 'cable',      kind: 'wr', alias: ['crunch', 'abs', 'пресс'] },
  { id: 'woodchopper',     en: 'Cable Woodchopper',         ru: 'Дровосек на блоке',              m: 'core', eq: 'cable',      kind: 'wr', alias: ['woodchop', 'chop'] },
  { id: 'ab-wheel',        en: 'Ab Wheel Rollout',          ru: 'Ролик для пресса',               m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['rollout', 'abs', 'пресс'] },
  { id: 'russian-twist',   en: 'Russian Twist',             ru: 'Русские скручивания',            m: 'core', eq: 'bodyweight', kind: 'reps' },
  { id: 'dead-bug',        en: 'Dead Bug',                  ru: 'Упражнение «мёртвый жук»',       m: 'core', eq: 'bodyweight', kind: 'reps' },
  { id: 'side-plank',      en: 'Side Plank',                ru: 'Боковая планка',                 m: 'core', eq: 'bodyweight', kind: 'time' },

  // ---- Forearms ----
  { id: 'wrist-curl',      en: 'Wrist Curl',                ru: 'Сгибания запястий',              m: 'forearms', eq: 'dumbbell', kind: 'wr' },
  { id: 'farmers-carry',   en: "Farmer's Carry",            ru: 'Прогулка фермера',               m: 'forearms', eq: 'dumbbell', kind: 'time', alias: ['farmer walk', 'carry'] },

  // ---- Cardio ----
  { id: 'treadmill',       en: 'Treadmill Walk',            ru: 'Ходьба на дорожке',              m: 'cardio', eq: 'machine', kind: 'time', alias: ['cardio', 'walk'] },
  { id: 'bike',            en: 'Stationary Bike',           ru: 'Велотренажёр',                   m: 'cardio', eq: 'machine', kind: 'time', alias: ['cycling', 'cardio'] },
  { id: 'rowing',          en: 'Rowing Machine',            ru: 'Гребной тренажёр',               m: 'cardio', eq: 'machine', kind: 'time', alias: ['erg', 'rower', 'cardio'] },
  { id: 'elliptical',      en: 'Elliptical',                ru: 'Эллиптический тренажёр',         m: 'cardio', eq: 'machine', kind: 'time', alias: ['cardio'] },
  { id: 'stair-climber',   en: 'Stair Climber',             ru: 'Степпер',                        m: 'cardio', eq: 'machine', kind: 'time', alias: ['stairs', 'stairmaster', 'cardio'] },
];

// Templates preloaded from Artem's mass-gain program (full-body A/B)
const SEED_TEMPLATES = [
  {
    id: 'tpl-day-a', name: 'Day A', name_ru: 'День A', seeded: true,
    items: [
      { exId: 'leg-press',      sets: 3, lo: 8,  hi: 12, note: 'Machine, back supported' },
      { exId: 'db-incline',     sets: 3, lo: 8,  hi: 12, note: 'Controlled load — protects shoulder' },
      { exId: 'seated-row',     sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'lying-leg-curl', sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'lateral-raise',  sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'woodchopper',    sets: 3, lo: 10, hi: 15, note: 'Core' },
    ],
  },
  {
    id: 'tpl-day-b', name: 'Day B', name_ru: 'День B', seeded: true,
    items: [
      { exId: 'db-rdl',           sets: 3, lo: 8,  hi: 10, note: 'Strict form, no spinal rounding' },
      { exId: 'lat-pulldown',     sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'db-shoulder',      sets: 3, lo: 8,  hi: 12, note: 'Controlled load' },
      { exId: 'cs-row',           sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'leg-extension',    sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'hanging-leg-raise',sets: 3, lo: 8,  hi: 15, note: 'Core' },
    ],
  },
];

const I18N = {
  en: {
    app: 'GymLog',
    tab_home: 'Today', tab_history: 'History', tab_exercises: 'Exercises', tab_stats: 'Stats', tab_body: 'Body',
    settings: 'Settings',
    start_empty: 'Start empty workout', start_from: 'Start from template',
    resume: 'Resume workout', in_progress: 'Workout in progress',
    no_workouts: 'No workouts logged yet.',
    last_workout: 'Last workout', this_week: 'This week', sessions: 'sessions',
    add_exercise: 'Add exercise', add_set: 'Add set', finish: 'Finish', discard: 'Discard',
    weight: 'Weight', reps: 'Reps', time: 'Time', set: 'Set', prev: 'Prev', rir: 'RIR',
    notes: 'Notes', note_ph: 'Notes…', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
    close: 'Close', done: 'Done', all: 'All', search: 'Search…',
    new_exercise: 'New exercise', name: 'Name', muscle: 'Muscle group', equipment: 'Equipment',
    type: 'Tracking type', type_wr: 'Weight × reps', type_reps: 'Reps only', type_time: 'Duration',
    description: 'Description',
    templates: 'Templates', save_as_template: 'Save as template', template_name: 'Template name',
    no_templates: 'No templates yet.',
    workout_name: 'Workout name',
    volume: 'Volume', total_volume: 'Total volume', workouts: 'Workouts', streak: 'Streak', weeks: 'wks',
    best_set: 'Best set', est_1rm: 'Est. 1RM', per_exercise: 'Per exercise', overall: 'Overall',
    last_12_weeks: 'Volume — last 12 weeks', muscle_split: 'Muscle split — last 30 days',
    avg_per_week: 'Avg / week', duration: 'Duration', min: 'min',
    body_weight: 'Body weight', log_weight: 'Log weight', measurements: 'Measurements',
    waist: 'Waist', chest_m: 'Chest', arm: 'Arm', thigh: 'Thigh', neck: 'Neck',
    goal: 'Goal', start_w: 'Start', current: 'Current', to_go: 'To go', trend7: '7-day avg',
    weekly_change: 'Weekly change', target_rate: 'target 0.18–0.20 kg/wk',
    lang: 'Language', theme: 'Theme', dark: 'Dark', light: 'Light',
    rest_timer: 'Rest timer', rest_default: 'Default rest', vibrate: 'Sound / vibration on finish',
    repeat: 'Repeat workout', exercises_n: 'exercises',
    front: 'Front', back_view: 'Back', primary: 'Primary', secondary: 'Also works',
    how_to: 'How to perform (YouTube)', info: 'How to / info',
    new_template: 'New template', edit_template: 'Edit template', duplicate: 'Duplicate',
    sets_target: 'Sets', rep_range: 'Reps', tpl_empty: 'Add exercises to this template.',
    tpl_name_required: 'Give the template a name.', new: 'New',
    progression: 'Progression hints', plate_calc: 'Plate calculator', program_warn: 'Program warnings',
    bar_weight: 'Bar weight', data: 'Data', export: 'Export backup (JSON)', import: 'Import backup',
    wipe: 'Erase all data', wipe_confirm: 'Erase everything? This cannot be undone.',
    last_backup: 'Last backup', never: 'never', days_ago: 'd ago', today: 'today',
    backup_due: 'No backup in {n} days — export one.',
    progression_hit: 'Top of rep range hit on all sets → add weight next session.',
    warn_back: 'Your program flags this: axial spinal load. Prefer leg press / hack squat / machine squat.',
    warn_shoulder: 'Your program flags this: shoulder risk. Prefer dumbbell press with moderate load.',
    plates_per_side: 'Per side', target_weight: 'Target weight',
    empty_stats: 'Log a few workouts to see stats.',
    confirm_delete: 'Delete this?', custom: 'Custom', seeded_program: 'From your program',
    kg: 'kg', cm: 'cm', sets_short: 'sets', imported: 'Backup imported.', import_failed: 'Import failed — invalid file.',
    exercise_exists: 'An exercise with this name already exists.',
    pick_template: 'Pick a template', quick_add: 'Quick add', history_for: 'History',
    no_history_ex: 'No history for this exercise yet.',
    week: 'Week', total: 'Total', sets_done: 'sets', reps_total: 'reps',
    finish_confirm: 'Finish and save this workout?', discard_confirm: 'Discard this workout? Nothing will be saved.',
    empty_workout: 'Add at least one set before finishing.',
    rest: 'Rest', skip: 'Skip', add30: '+30s',
    program_note: 'Program', trend: 'Trend',
    log_set: 'Log set {n}', set_n: 'Set {n}', last: 'Last', on_target: 'On target', warmup: 'Warm-up',
    unit_reps: 'reps', unit_sec: 'sec', unit_pluskg: '+kg',
    hint_steps: 'Steps of {n}', hint_hold: 'hold for {n}', hint_hold_repeat: 'hold to repeat', hint_type: 'tap a number to type',
    set_deleted: 'Set {n} deleted', undo: 'Undo', delete_now: 'Delete now',
    mark_warm: 'Mark as warm-up', mark_working: 'Mark as working set', edit_set: 'Edit this set', delete_set: 'Delete set',
    exercise_options: 'Exercise options', move_up: 'Move up', move_down: 'Move down', search_ex: 'Search · RDL, OHP, жим',
    this_session: 'This session', discard_workout: 'Discard workout',
    reps_lo: 'Reps from', reps_hi: 'Reps to',
    hidden_ex: 'Hidden exercises', restore: 'Restore', db_step: 'Dumbbell step',
    vol_12w: 'Volume · 12 weeks', tonnes: 'tonnes', split_30: 'Muscle split · 30 days',
    empty_log_t: 'An empty session.', empty_log_s: 'Add the first exercise to start logging.',
    empty_hist_t: 'Every finished workout lands here.', empty_hist_s: 'Start one from Today. It appears here after you tap Finish.',
    empty_stats_t: 'Trends appear after a few sessions.', empty_stats_s: 'Log and finish a workout to start the charts.',
    empty_ex_t: 'Nothing matches that search.', empty_ex_s: 'Try a short name like RDL or жим, or add it as a new exercise.',
    empty_tpl_t: 'No templates yet.', empty_tpl_s: 'Create one and start a whole workout with one tap.',
    empty_body_t: 'No weigh-ins yet.', empty_body_s: 'Log your weight above. The 7-day trend starts after two entries.',
    empty_exhist_s: 'It shows up here after you log it once.',
    plates_left: 'Not exact with your plates: {n} kg left over',
    version: 'GymLog · v3 · data stays on this device',
    date: 'Date',
    sess_one: '{n} session', sess_many: '{n} sessions', exn_one: '{n} exercise', exn_many: '{n} exercises',
  },
  ru: {
    app: 'GymLog',
    tab_home: 'Сегодня', tab_history: 'История', tab_exercises: 'Упражнения', tab_stats: 'Статистика', tab_body: 'Тело',
    settings: 'Настройки',
    start_empty: 'Начать пустую тренировку', start_from: 'Начать по шаблону',
    resume: 'Продолжить тренировку', in_progress: 'Тренировка идёт',
    no_workouts: 'Пока нет тренировок.',
    last_workout: 'Последняя тренировка', this_week: 'На этой неделе', sessions: 'тренировок',
    add_exercise: 'Добавить упражнение', add_set: 'Добавить подход', finish: 'Завершить', discard: 'Отменить',
    weight: 'Вес', reps: 'Повт.', time: 'Время', set: 'Подход', prev: 'Пред.', rir: 'RIR',
    notes: 'Заметки', note_ph: 'Заметки…', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить',
    close: 'Закрыть', done: 'Готово', all: 'Все', search: 'Поиск…',
    new_exercise: 'Новое упражнение', name: 'Название', muscle: 'Мышечная группа', equipment: 'Оборудование',
    type: 'Тип учёта', type_wr: 'Вес × повторы', type_reps: 'Только повторы', type_time: 'Длительность',
    description: 'Описание',
    templates: 'Шаблоны', save_as_template: 'Сохранить как шаблон', template_name: 'Название шаблона',
    no_templates: 'Шаблонов пока нет.',
    workout_name: 'Название тренировки',
    volume: 'Объём', total_volume: 'Общий объём', workouts: 'Тренировки', streak: 'Серия', weeks: 'нед.',
    best_set: 'Лучший подход', est_1rm: 'Расч. 1ПМ', per_exercise: 'По упражнению', overall: 'Общая',
    last_12_weeks: 'Объём — последние 12 недель', muscle_split: 'По группам — 30 дней',
    avg_per_week: 'В среднем / нед.', duration: 'Длительность', min: 'мин',
    body_weight: 'Вес тела', log_weight: 'Записать вес', measurements: 'Замеры',
    waist: 'Талия', chest_m: 'Грудь', arm: 'Рука', thigh: 'Бедро', neck: 'Шея',
    goal: 'Цель', start_w: 'Старт', current: 'Сейчас', to_go: 'Осталось', trend7: 'Среднее за 7 дней',
    weekly_change: 'Изменение за неделю', target_rate: 'цель 0,18–0,20 кг/нед.',
    lang: 'Язык', theme: 'Тема', dark: 'Тёмная', light: 'Светлая',
    rest_timer: 'Таймер отдыха', rest_default: 'Отдых по умолчанию', vibrate: 'Звук / вибрация по окончании',
    repeat: 'Повторить тренировку', exercises_n: 'упражнений',
    front: 'Спереди', back_view: 'Сзади', primary: 'Основная', secondary: 'Дополнительно',
    how_to: 'Как выполнять (YouTube)', info: 'Техника / инфо',
    new_template: 'Новый шаблон', edit_template: 'Изменить шаблон', duplicate: 'Дублировать',
    sets_target: 'Подходы', rep_range: 'Повторы', tpl_empty: 'Добавьте упражнения в шаблон.',
    tpl_name_required: 'Укажите название шаблона.', new: 'Новый',
    progression: 'Подсказки прогрессии', plate_calc: 'Калькулятор блинов', program_warn: 'Предупреждения программы',
    bar_weight: 'Вес грифа', data: 'Данные', export: 'Экспорт резервной копии (JSON)', import: 'Импорт копии',
    wipe: 'Удалить все данные', wipe_confirm: 'Удалить всё? Это необратимо.',
    last_backup: 'Последняя копия', never: 'никогда', days_ago: ' дн. назад', today: 'сегодня',
    backup_due: 'Копии не было {n} дн. — сделайте экспорт.',
    progression_hit: 'Верх диапазона взят во всех подходах → добавьте вес в следующий раз.',
    warn_back: 'Программа не рекомендует: осевая нагрузка на позвоночник. Лучше жим ногами / гакк / присед в тренажёре.',
    warn_shoulder: 'Программа не рекомендует: риск для плеча. Лучше жим гантелей с умеренным весом.',
    plates_per_side: 'На сторону', target_weight: 'Целевой вес',
    empty_stats: 'Запишите несколько тренировок, чтобы увидеть статистику.',
    confirm_delete: 'Удалить?', custom: 'Своё', seeded_program: 'Из вашей программы',
    kg: 'кг', cm: 'см', sets_short: 'подх.', imported: 'Копия загружена.', import_failed: 'Ошибка импорта — неверный файл.',
    exercise_exists: 'Упражнение с таким названием уже есть.',
    pick_template: 'Выберите шаблон', quick_add: 'Быстрое добавление', history_for: 'История',
    no_history_ex: 'Пока нет истории по этому упражнению.',
    week: 'Неделя', total: 'Всего', sets_done: 'подх.', reps_total: 'повт.',
    finish_confirm: 'Завершить и сохранить тренировку?', discard_confirm: 'Отменить тренировку? Ничего не сохранится.',
    empty_workout: 'Добавьте хотя бы один подход перед завершением.',
    rest: 'Отдых', skip: 'Пропустить', add30: '+30 с',
    program_note: 'Программа', trend: 'Тренд',
    log_set: 'Записать подход {n}', set_n: 'Подход {n}', last: 'Прошлый', on_target: 'В диапазоне', warmup: 'Разминка',
    unit_reps: 'повт.', unit_sec: 'сек', unit_pluskg: '+кг',
    hint_steps: 'Шаг {n}', hint_hold: 'удержание: {n}', hint_hold_repeat: 'удерживайте для повтора', hint_type: 'нажмите на число для ввода',
    set_deleted: 'Подход {n} удалён', undo: 'Вернуть', delete_now: 'Удалить сразу',
    mark_warm: 'Отметить как разминку', mark_working: 'Сделать рабочим подходом', edit_set: 'Изменить подход', delete_set: 'Удалить подход',
    exercise_options: 'Действия с упражнением', move_up: 'Выше', move_down: 'Ниже', search_ex: 'Поиск · RDL, OHP, жим',
    this_session: 'Эта тренировка', discard_workout: 'Отменить тренировку',
    reps_lo: 'Повт. от', reps_hi: 'Повт. до',
    hidden_ex: 'Скрытые упражнения', restore: 'Вернуть', db_step: 'Шаг гантелей',
    vol_12w: 'Объём · 12 недель', tonnes: 'тонн', split_30: 'По группам · 30 дней',
    empty_log_t: 'Пустая тренировка.', empty_log_s: 'Добавьте первое упражнение, чтобы начать запись.',
    empty_hist_t: 'Здесь появятся завершённые тренировки.', empty_hist_s: 'Начните тренировку на вкладке «Сегодня». Она появится здесь после «Завершить».',
    empty_stats_t: 'Тренды появятся после нескольких тренировок.', empty_stats_s: 'Запишите и завершите тренировку, чтобы начать графики.',
    empty_ex_t: 'Ничего не найдено.', empty_ex_s: 'Попробуйте короткое название, например RDL или жим, или добавьте новое упражнение.',
    empty_tpl_t: 'Шаблонов пока нет.', empty_tpl_s: 'Создайте шаблон и начинайте всю тренировку одним нажатием.',
    empty_body_t: 'Пока нет записей веса.', empty_body_s: 'Запишите вес выше. Тренд за 7 дней появится после двух записей.',
    empty_exhist_s: 'История появится после первой записи.',
    plates_left: 'Не набирается точно: остаётся {n} кг',
    version: 'GymLog · v3 · данные хранятся только на этом устройстве',
    date: 'Дата',
    sess_one: '{n} тренировка', sess_few: '{n} тренировки', sess_many: '{n} тренировок', exn_one: '{n} упражнение', exn_few: '{n} упражнения', exn_many: '{n} упражнений',
  },
};
