/* FREILIFT — seed data: muscle groups, equipment, exercise library, i18n */

const MUSCLES = [
  { id: 'chest',      en: 'Chest',      ru: 'Грудь' },
  { id: 'back',       en: 'Back',       ru: 'Спина' },
  { id: 'shoulders',  en: 'Shoulders',  ru: 'Плечи' },
  { id: 'biceps',     en: 'Biceps',     ru: 'Бицепс' },
  { id: 'triceps',    en: 'Triceps',    ru: 'Трицепс' },
  { id: 'forearms',   en: 'Forearms',   ru: 'Предплечья' },
  { id: 'quads',      en: 'Quads',      ru: 'Квадрицепс' },
  { id: 'hamstrings', en: 'Hamstrings', ru: 'Бицепс бедра' },
  { id: 'glutes',     en: 'Glutes',     ru: 'Ягодицы' },
  { id: 'calves',     en: 'Calves',     ru: 'Икры' },
  { id: 'core',       en: 'Core',       ru: 'Кор / Пресс' },
  { id: 'cardio',     en: 'Cardio',     ru: 'Кардио' },
];

const EQUIPMENT = [
  { id: 'barbell',    en: 'Barbell',    ru: 'Штанга' },
  { id: 'dumbbell',   en: 'Dumbbell',   ru: 'Гантели' },
  { id: 'machine',    en: 'Machine',    ru: 'Тренажёр' },
  { id: 'cable',      en: 'Cable',      ru: 'Блок' },
  { id: 'bodyweight', en: 'Bodyweight', ru: 'Свой вес' },
  { id: 'smith',      en: 'Smith machine', ru: 'Машина Смита' },
  { id: 'kettlebell', en: 'Kettlebell', ru: 'Гиря' },
  { id: 'band',       en: 'Band',       ru: 'Резинка' },
  { id: 'other',      en: 'Other',      ru: 'Другое' },
];

// kind: 'wr' = weight x reps | 'reps' = reps only (weight optional) | 'time' = duration
// warn: 'back' | 'shoulder'  -> flagged against Artem's program constraints
const SEED_EXERCISES = [
  // ---- Chest ----
  { id: 'bb-bench',        en: 'Barbell Bench Press',       ru: 'Жим штанги лёжа',                m: 'chest', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['bench', 'bp', 'жим лежа'] },
  { id: 'bb-incline',      en: 'Incline Barbell Press',     ru: 'Жим штанги на наклонной',        m: 'chest', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['incline bench', 'bench'] },
  { id: 'db-bench',        en: 'Dumbbell Bench Press',      ru: 'Жим гантелей лёжа',              m: 'chest', eq: 'dumbbell',   kind: 'wr', alias: ['bench', 'db bench'] },
  { id: 'db-incline',      en: 'Incline Dumbbell Press',    ru: 'Жим гантелей на наклонной',      m: 'chest', eq: 'dumbbell',   kind: 'wr', alias: ['incline', 'db incline', 'bench'] },
  { id: 'machine-press',   en: 'Machine Chest Press',       ru: 'Жим в тренажёре',                m: 'chest', eq: 'machine',    kind: 'wr', alias: ['chest press'] },
  { id: 'pec-deck',        en: 'Pec Deck / Machine Fly',    ru: 'Сведения в тренажёре («бабочка»)', m: 'chest', eq: 'machine',  kind: 'wr', alias: ['fly', 'butterfly', 'бабочка'] },
  { id: 'cable-fly',       en: 'Cable Fly',                 ru: 'Сведения в кроссовере',          m: 'chest', eq: 'cable',      kind: 'wr', alias: ['fly', 'crossover', 'кроссовер'] },
  { id: 'push-up',         en: 'Push-Up',                   ru: 'Отжимания от пола',              m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['pushup', 'отжимания'] },
  { id: 'chest-dip',       en: 'Chest Dip',                 ru: 'Отжимания на брусьях (грудь)',   m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['dips', 'брусья'] },

  // ---- Back ----
  { id: 'lat-pulldown',    en: 'Lat Pulldown',              ru: 'Тяга верхнего блока',            m: 'back', eq: 'machine',    kind: 'wr', alias: ['pulldown', 'lpd', 'тяга блока'] },
  { id: 'pull-up',         en: 'Pull-Up',                   ru: 'Подтягивания',                   m: 'back', eq: 'bodyweight', kind: 'reps', alias: ['pullup', 'chin-up', 'chinup', 'турник'] },
  { id: 'assisted-pullup', en: 'Assisted Pull-Up',          ru: 'Подтягивания в гравитроне',      m: 'back', eq: 'machine',    kind: 'wr', alias: ['gravitron', 'гравитрон', 'pullup'] },
  { id: 'seated-row',      en: 'Seated Cable Row',          ru: 'Тяга нижнего блока сидя',        m: 'back', eq: 'cable',      kind: 'wr', alias: ['row', 'cable row', 'low row'] },
  { id: 'cs-row',          en: 'Chest-Supported Row',       ru: 'Тяга с упором в грудь',          m: 'back', eq: 'machine',    kind: 'wr', alias: ['row', 'seal row'] },
  { id: 'bb-row',          en: 'Barbell Row',               ru: 'Тяга штанги в наклоне',          m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['row', 'bent over row', 'bor'] },
  { id: 'db-row',          en: 'One-Arm Dumbbell Row',      ru: 'Тяга гантели в наклоне',         m: 'back', eq: 'dumbbell',   kind: 'wr', alias: ['row', 'db row'] },
  { id: 't-bar-row',       en: 'T-Bar Row',                 ru: 'Т-тяга',                         m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['row', 't bar', 'tbar'] },
  { id: 'sa-pulldown',     en: 'Straight-Arm Pulldown',     ru: 'Пуловер на верхнем блоке',       m: 'back', eq: 'cable',      kind: 'wr', alias: ['pulldown', 'pullover', 'пуловер'] },
  { id: 'deadlift',        en: 'Conventional Deadlift',     ru: 'Становая тяга',                  m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['dl', 'deadlift', 'становая'] },
  { id: 'rack-pull',       en: 'Rack Pull',                 ru: 'Тяга с плинтов',                 m: 'back', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['dl', 'rack pull'] },
  { id: 'db-shrug',        en: 'Dumbbell Shrug',            ru: 'Шраги с гантелями',              m: 'back', eq: 'dumbbell',   kind: 'wr', alias: ['shrug', 'шраги'] },

  // ---- Shoulders ----
  { id: 'db-shoulder',     en: 'Dumbbell Shoulder Press',   ru: 'Жим гантелей сидя',              m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['ohp', 'shoulder press', 'db ohp'] },
  { id: 'bb-ohp',          en: 'Barbell Overhead Press',    ru: 'Жим штанги стоя',                m: 'shoulders', eq: 'barbell',  kind: 'wr', warn: 'shoulder', alias: ['ohp', 'military press', 'overhead press', 'армейский жим'] },
  { id: 'machine-shoulder',en: 'Machine Shoulder Press',    ru: 'Жим в тренажёре сидя',           m: 'shoulders', eq: 'machine',  kind: 'wr', alias: ['shoulder press', 'ohp'] },
  { id: 'lateral-raise',   en: 'Lateral Raise',             ru: 'Махи гантелями в стороны',       m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['lat raise', 'side raise', 'махи'] },
  { id: 'cable-lateral',   en: 'Cable Lateral Raise',       ru: 'Махи в стороны на блоке',        m: 'shoulders', eq: 'cable',    kind: 'wr', alias: ['lat raise', 'side raise'] },
  { id: 'rear-delt-fly',   en: 'Rear Delt Fly',             ru: 'Махи в наклоне (задняя дельта)', m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['reverse fly', 'rear delt'] },
  { id: 'face-pull',       en: 'Face Pull',                 ru: 'Тяга к лицу',                    m: 'shoulders', eq: 'cable',    kind: 'wr', alias: ['facepull'] },
  { id: 'front-raise',     en: 'Front Raise',               ru: 'Подъём гантелей перед собой',    m: 'shoulders', eq: 'dumbbell', kind: 'wr' },
  { id: 'upright-row',     en: 'Upright Row',               ru: 'Тяга к подбородку',              m: 'shoulders', eq: 'barbell',  kind: 'wr', warn: 'shoulder' },

  // ---- Biceps ----
  { id: 'bb-curl',         en: 'Barbell Curl',              ru: 'Подъём штанги на бицепс',        m: 'biceps', eq: 'barbell',  kind: 'wr', alias: ['curl', 'bicep curl'] },
  { id: 'db-curl',         en: 'Dumbbell Curl',             ru: 'Подъём гантелей на бицепс',      m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'bicep curl'] },
  { id: 'hammer-curl',     en: 'Hammer Curl',               ru: 'Молотковые сгибания',            m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'молотки'] },
  { id: 'incline-curl',    en: 'Incline Dumbbell Curl',     ru: 'Сгибания на наклонной скамье',   m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl'] },
  { id: 'preacher-curl',   en: 'Preacher Curl',             ru: 'Сгибания на скамье Скотта',      m: 'biceps', eq: 'machine',  kind: 'wr', alias: ['curl', 'скотт'] },
  { id: 'cable-curl',      en: 'Cable Curl',                ru: 'Сгибания на нижнем блоке',       m: 'biceps', eq: 'cable',    kind: 'wr', alias: ['curl'] },

  // ---- Triceps ----
  { id: 'pushdown',        en: 'Triceps Pushdown',          ru: 'Разгибания на блоке',            m: 'triceps', eq: 'cable',      kind: 'wr', alias: ['tricep pushdown', 'pressdown'] },
  { id: 'rope-pushdown',   en: 'Rope Pushdown',             ru: 'Разгибания с канатом',           m: 'triceps', eq: 'cable',      kind: 'wr', alias: ['tricep pushdown', 'pressdown', 'rope'] },
  { id: 'oh-triceps',      en: 'Overhead Triceps Extension',ru: 'Французский жим стоя',           m: 'triceps', eq: 'dumbbell',   kind: 'wr', alias: ['french press', 'overhead extension', 'французский'] },
  { id: 'skullcrusher',    en: 'Skullcrusher',              ru: 'Французский жим лёжа',           m: 'triceps', eq: 'barbell',    kind: 'wr', alias: ['skull crusher', 'french press', 'lying extension', 'французский'] },
  { id: 'cg-bench',        en: 'Close-Grip Bench Press',    ru: 'Жим узким хватом',               m: 'triceps', eq: 'barbell',    kind: 'wr', warn: 'shoulder', alias: ['cgbp', 'close grip', 'bench'] },
  { id: 'triceps-dip',     en: 'Triceps Dip',               ru: 'Отжимания на брусьях (трицепс)', m: 'triceps', eq: 'bodyweight', kind: 'reps', alias: ['dips', 'брусья'] },
  { id: 'bench-dip',       en: 'Bench Dip',                 ru: 'Обратные отжимания от скамьи',   m: 'triceps', eq: 'bodyweight', kind: 'reps' },

  // ---- Quads ----
  { id: 'leg-press',       en: 'Leg Press',                 ru: 'Жим ногами',                     m: 'quads', eq: 'machine',    kind: 'wr', alias: ['lp', 'жим ногами'] },
  { id: 'hack-squat',      en: 'Hack Squat',                ru: 'Гакк-приседания',                m: 'quads', eq: 'machine',    kind: 'wr', alias: ['squat', 'гакк'] },
  { id: 'machine-squat',   en: 'Machine Squat',             ru: 'Присед в тренажёре',             m: 'quads', eq: 'machine',    kind: 'wr', alias: ['squat', 'smith'] },
  { id: 'back-squat',      en: 'Barbell Back Squat',        ru: 'Присед со штангой',              m: 'quads', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['squat', 'bb squat'] },
  { id: 'front-squat',     en: 'Front Squat',               ru: 'Фронтальный присед',             m: 'quads', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['squat'] },
  { id: 'goblet-squat',    en: 'Goblet Squat',              ru: 'Гоблет-присед',                  m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['squat'] },
  { id: 'leg-extension',   en: 'Leg Extension',             ru: 'Разгибания ног сидя',            m: 'quads', eq: 'machine',    kind: 'wr', alias: ['extension', 'разгибания'] },
  { id: 'bulgarian',       en: 'Bulgarian Split Squat',     ru: 'Болгарский выпад',               m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['bss', 'split squat', 'болгарка'] },
  { id: 'lunge',           en: 'Walking Lunge',             ru: 'Выпады с гантелями',             m: 'quads', eq: 'dumbbell',   kind: 'wr', alias: ['lunges'] },

  // ---- Hamstrings ----
  { id: 'lying-leg-curl',  en: 'Lying Leg Curl',            ru: 'Сгибания ног лёжа',              m: 'hamstrings', eq: 'machine',    kind: 'wr', alias: ['leg curl', 'hamstring curl'] },
  { id: 'seated-leg-curl', en: 'Seated Leg Curl',           ru: 'Сгибания ног сидя',              m: 'hamstrings', eq: 'machine',    kind: 'wr', alias: ['leg curl', 'hamstring curl'] },
  { id: 'db-rdl',          en: 'Dumbbell Romanian Deadlift',ru: 'Румынская тяга с гантелями',     m: 'hamstrings', eq: 'dumbbell',   kind: 'wr', alias: ['rdl', 'sldl', 'db rdl', 'румынка'] },
  { id: 'bb-rdl',          en: 'Barbell Romanian Deadlift', ru: 'Румынская тяга со штангой',      m: 'hamstrings', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['rdl', 'sldl', 'bb rdl', 'румынка'] },
  { id: 'good-morning',    en: 'Good Morning',              ru: 'Наклоны со штангой',             m: 'hamstrings', eq: 'barbell',    kind: 'wr', warn: 'back', alias: ['gm'] },
  { id: 'nordic-curl',     en: 'Nordic Curl',               ru: 'Нордические сгибания',           m: 'hamstrings', eq: 'bodyweight', kind: 'reps', alias: ['nordic', 'leg curl'] },

  // ---- Glutes ----
  { id: 'hip-thrust',      en: 'Barbell Hip Thrust',        ru: 'Ягодичный мост со штангой',      m: 'glutes', eq: 'barbell', kind: 'wr', alias: ['glute bridge', 'мостик'] },
  { id: 'hip-thrust-mach', en: 'Hip Thrust Machine',        ru: 'Ягодичный мост в тренажёре',     m: 'glutes', eq: 'machine', kind: 'wr', alias: ['glute bridge', 'hip thrust', 'мостик'] },
  { id: 'kickback',        en: 'Cable Glute Kickback',      ru: 'Отведение ноги назад на блоке',  m: 'glutes', eq: 'cable',   kind: 'wr', alias: ['glute kickback'] },
  { id: 'hip-abduction',   en: 'Hip Abduction Machine',     ru: 'Разведение ног в тренажёре',     m: 'glutes', eq: 'machine', kind: 'wr', alias: ['abductor', 'abduction'] },

  // ---- Calves ----
  { id: 'standing-calf',   en: 'Standing Calf Raise',       ru: 'Подъём на носки стоя',           m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },
  { id: 'seated-calf',     en: 'Seated Calf Raise',         ru: 'Подъём на носки сидя',           m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },
  { id: 'leg-press-calf',  en: 'Leg Press Calf Raise',      ru: 'Носки в жиме ногами',            m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'calves', 'икры'] },

  // ---- Core ----
  { id: 'plank',           en: 'Plank',                     ru: 'Планка',                         m: 'core', eq: 'bodyweight', kind: 'time' },
  { id: 'hanging-leg-raise',en:'Hanging Leg Raise',         ru: 'Подъём ног в висе',              m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['hlr', 'leg raise'] },
  { id: 'cable-crunch',    en: 'Cable Crunch',              ru: 'Скручивания на блоке',           m: 'core', eq: 'cable',      kind: 'wr', alias: ['crunch', 'abs', 'пресс'] },
  { id: 'woodchopper',     en: 'Cable Woodchopper',         ru: 'Дровосек на блоке',              m: 'core', eq: 'cable',      kind: 'wr', alias: ['woodchop', 'chop'] },
  { id: 'ab-wheel',        en: 'Ab Wheel Rollout',          ru: 'Ролик для пресса',               m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['rollout', 'abs', 'пресс'] },
  { id: 'russian-twist',   en: 'Russian Twist',             ru: 'Русские скручивания',            m: 'core', eq: 'bodyweight', kind: 'reps' },
  { id: 'dead-bug',        en: 'Dead Bug',                  ru: 'Упражнение «мёртвый жук»',       m: 'core', eq: 'bodyweight', kind: 'reps' },
  { id: 'side-plank',      en: 'Side Plank',                ru: 'Боковая планка',                 m: 'core', eq: 'bodyweight', kind: 'time' },

  // ---- Forearms ----
  { id: 'wrist-curl',      en: 'Wrist Curl',                ru: 'Сгибания запястий',              m: 'forearms', eq: 'dumbbell', kind: 'wr' },
  { id: 'farmers-carry',   en: "Farmer's Carry",            ru: 'Прогулка фермера',               m: 'forearms', eq: 'dumbbell', kind: 'time', alias: ['farmer walk', 'carry'] },

  // ---- Cardio ----
  { id: 'treadmill',       en: 'Treadmill Walk',            ru: 'Ходьба на дорожке',              m: 'cardio', eq: 'machine', kind: 'time', alias: ['cardio', 'walk'] },
  { id: 'bike',            en: 'Stationary Bike',           ru: 'Велотренажёр',                   m: 'cardio', eq: 'machine', kind: 'time', alias: ['cycling', 'cardio'] },
  { id: 'rowing',          en: 'Rowing Machine',            ru: 'Гребной тренажёр',               m: 'cardio', eq: 'machine', kind: 'time', alias: ['erg', 'rower', 'cardio'] },
  { id: 'elliptical',      en: 'Elliptical',                ru: 'Эллиптический тренажёр',         m: 'cardio', eq: 'machine', kind: 'time', alias: ['cardio'] },
  { id: 'stair-climber',   en: 'Stair Climber',             ru: 'Степпер',                        m: 'cardio', eq: 'machine', kind: 'time', alias: ['stairs', 'stairmaster', 'cardio'] },

  // ======== added in v3.4: wider library ========
  // ---- Chest ----
  { id: 'decline-bench', en: 'Decline Barbell Press', ru: 'Жим штанги на скамье с отрицательным наклоном', m: 'chest', eq: 'barbell', kind: 'wr', warn: 'shoulder', alias: ['decline', 'decline bench', 'bench'] },
  { id: 'db-fly', en: 'Dumbbell Fly', ru: 'Разведения гантелей лёжа', m: 'chest', eq: 'dumbbell', kind: 'wr', alias: ['fly', 'flyes', 'разводка'] },
  { id: 'incline-db-fly', en: 'Incline Dumbbell Fly', ru: 'Разведения гантелей на наклонной скамье', m: 'chest', eq: 'dumbbell', kind: 'wr', alias: ['incline fly', 'fly', 'разводка'] },
  { id: 'smith-bench', en: 'Smith Machine Bench Press', ru: 'Жим лёжа в машине Смита', m: 'chest', eq: 'smith', kind: 'wr', warn: 'shoulder', alias: ['smith bench', 'bench', 'смит'] },
  { id: 'smith-incline', en: 'Incline Smith Machine Press', ru: 'Жим на наклонной скамье в машине Смита', m: 'chest', eq: 'smith', kind: 'wr', warn: 'shoulder', alias: ['smith incline', 'incline', 'смит'] },
  { id: 'incline-machine-press', en: 'Incline Machine Press', ru: 'Жим на наклонной в тренажёре', m: 'chest', eq: 'machine', kind: 'wr', alias: ['incline press', 'chest press'] },
  { id: 'landmine-press', en: 'Landmine Press', ru: 'Жим штанги в лендмайне', m: 'chest', eq: 'barbell', kind: 'wr', alias: ['landmine', 'лендмайн'] },
  { id: 'cable-crossover-high', en: 'High-to-Low Cable Crossover', ru: 'Сведения в кроссовере сверху вниз', m: 'chest', eq: 'cable', kind: 'wr', alias: ['crossover', 'fly', 'кроссовер'] },
  { id: 'low-cable-fly', en: 'Low-to-High Cable Fly', ru: 'Сведения в кроссовере снизу вверх', m: 'chest', eq: 'cable', kind: 'wr', alias: ['crossover', 'fly', 'upper chest', 'кроссовер'] },
  { id: 'weighted-push-up', en: 'Weighted Push-Up', ru: 'Отжимания с отягощением', m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['pushup', 'push up', 'отжимания'] },
  { id: 'incline-push-up', en: 'Incline Push-Up', ru: 'Отжимания с упором руками на скамью', m: 'chest', eq: 'bodyweight', kind: 'reps', alias: ['pushup', 'push up', 'отжимания'] },
  // ---- Back ----
  { id: 'chin-up', en: 'Chin-Up', ru: 'Подтягивания обратным хватом', m: 'back', eq: 'bodyweight', kind: 'reps', alias: ['chinup', 'chin up', 'подтягивания'] },
  { id: 'neutral-pulldown', en: 'Neutral-Grip Pulldown', ru: 'Тяга верхнего блока узким параллельным хватом', m: 'back', eq: 'machine', kind: 'wr', alias: ['pulldown', 'v-bar', 'тяга блока'] },
  { id: 'sa-lat-pulldown', en: 'Single-Arm Lat Pulldown', ru: 'Тяга верхнего блока одной рукой', m: 'back', eq: 'cable', kind: 'wr', alias: ['pulldown', 'one arm', 'тяга блока'] },
  { id: 'reverse-pulldown', en: 'Reverse-Grip Pulldown', ru: 'Тяга верхнего блока обратным хватом', m: 'back', eq: 'machine', kind: 'wr', alias: ['pulldown', 'underhand', 'тяга блока'] },
  { id: 'inverted-row', en: 'Inverted Row', ru: 'Австралийские подтягивания', m: 'back', eq: 'bodyweight', kind: 'reps', alias: ['australian pull-up', 'row', 'австралийские'] },
  { id: 'pendlay-row', en: 'Pendlay Row', ru: 'Тяга Пендлея', m: 'back', eq: 'barbell', kind: 'wr', warn: 'back', alias: ['row', 'пендлей'] },
  { id: 'seal-row', en: 'Seal Row', ru: 'Тяга штанги лёжа на высокой скамье', m: 'back', eq: 'barbell', kind: 'wr', alias: ['row', 'chest supported', 'сил'] },
  { id: 'machine-row', en: 'Machine Row', ru: 'Тяга в рычажном тренажёре сидя', m: 'back', eq: 'machine', kind: 'wr', alias: ['row', 'seated row', 'рычажная тяга'] },
  { id: 'wide-cable-row', en: 'Wide-Grip Cable Row', ru: 'Тяга нижнего блока широким хватом', m: 'back', eq: 'cable', kind: 'wr', alias: ['row', 'cable row', 'тяга блока'] },
  { id: 'bb-shrug', en: 'Barbell Shrug', ru: 'Шраги со штангой', m: 'back', eq: 'barbell', kind: 'wr', alias: ['shrug', 'traps', 'шраги'] },
  { id: 'trap-bar-deadlift', en: 'Trap Bar Deadlift', ru: 'Становая тяга с трэп-грифом', m: 'back', eq: 'barbell', kind: 'wr', warn: 'back', alias: ['dl', 'hex bar', 'deadlift', 'трэп'] },
  { id: 'sumo-deadlift', en: 'Sumo Deadlift', ru: 'Становая тяга сумо', m: 'back', eq: 'barbell', kind: 'wr', warn: 'back', alias: ['dl', 'sumo', 'deadlift', 'сумо'] },
  { id: 'back-extension', en: 'Back Extension (45°)', ru: 'Гиперэкстензия 45°', m: 'back', eq: 'bodyweight', kind: 'reps', alias: ['hyperextension', 'lower back', 'гиперэкстензия'] },
  { id: 'machine-back-ext', en: 'Back Extension Machine', ru: 'Разгибание спины в тренажёре', m: 'back', eq: 'machine', kind: 'wr', alias: ['lower back', 'hyperextension', 'гиперэкстензия'] },
  { id: 'db-pullover', en: 'Dumbbell Pullover', ru: 'Пуловер с гантелью лёжа', m: 'back', eq: 'dumbbell', kind: 'wr', alias: ['pullover', 'пуловер'] },
  // ---- Shoulders ----
  { id: 'arnold-press', en: 'Arnold Press', ru: 'Жим Арнольда', m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['arnold', 'ohp', 'арнольд'] },
  { id: 'reverse-pec-deck', en: 'Reverse Pec Deck', ru: 'Обратные разведения в тренажёре «бабочка»', m: 'shoulders', eq: 'machine', kind: 'wr', alias: ['rear delt', 'reverse fly', 'задняя дельта', 'бабочка'] },
  { id: 'machine-lateral', en: 'Machine Lateral Raise', ru: 'Махи в стороны в тренажёре', m: 'shoulders', eq: 'machine', kind: 'wr', alias: ['lat raise', 'side raise', 'махи'] },
  { id: 'cable-ext-rotation', en: 'Cable External Rotation', ru: 'Наружная ротация плеча на блоке', m: 'shoulders', eq: 'cable', kind: 'wr', alias: ['rotator cuff', 'external rotation', 'ротация', 'ротаторы'] },
  { id: 'band-pull-apart', en: 'Band Pull-Apart', ru: 'Разведение резинки перед грудью', m: 'shoulders', eq: 'band', kind: 'reps', alias: ['pull apart', 'rear delt', 'резинка'] },
  { id: 'plate-front-raise', en: 'Plate Front Raise', ru: 'Подъём блина перед собой', m: 'shoulders', eq: 'other', kind: 'wr', alias: ['front raise', 'plate', 'блин'] },
  { id: 'y-raise', en: 'Incline Y-Raise', ru: 'Подъём гантелей буквой Y на наклонной скамье', m: 'shoulders', eq: 'dumbbell', kind: 'wr', alias: ['y raise', 'y-raise', 'lower traps'] },
  { id: 'cable-rear-delt', en: 'Cable Rear Delt Fly', ru: 'Разведения на заднюю дельту в кроссовере', m: 'shoulders', eq: 'cable', kind: 'wr', alias: ['rear delt', 'reverse fly', 'задняя дельта'] },
  // ---- Biceps ----
  { id: 'ez-curl', en: 'EZ-Bar Curl', ru: 'Подъём EZ-штанги на бицепс', m: 'biceps', eq: 'barbell', kind: 'wr', alias: ['ez', 'ez curl', 'curl', 'кривой гриф'] },
  { id: 'concentration-curl', en: 'Concentration Curl', ru: 'Концентрированные сгибания с гантелью', m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'концентрированные'] },
  { id: 'spider-curl', en: 'Spider Curl', ru: 'Сгибания «паук» на наклонной скамье', m: 'biceps', eq: 'dumbbell', kind: 'wr', alias: ['curl', 'паук'] },
  { id: 'reverse-curl', en: 'Reverse-Grip Curl', ru: 'Сгибания рук обратным хватом', m: 'biceps', eq: 'barbell', kind: 'wr', alias: ['reverse curl', 'curl', 'обратный хват'] },
  { id: 'rope-hammer-curl', en: 'Rope Hammer Curl', ru: 'Молотковые сгибания с канатом на блоке', m: 'biceps', eq: 'cable', kind: 'wr', alias: ['hammer', 'rope', 'curl', 'молотки'] },
  { id: 'machine-curl', en: 'Machine Curl', ru: 'Сгибания рук в тренажёре', m: 'biceps', eq: 'machine', kind: 'wr', alias: ['curl', 'бицепс'] },
  { id: 'bayesian-curl', en: 'Behind-the-Body Cable Curl', ru: 'Сгибания на бицепс на блоке из-за спины', m: 'biceps', eq: 'cable', kind: 'wr', alias: ['bayesian', 'curl'] },
  // ---- Triceps ----
  { id: 'oh-cable-ext', en: 'Overhead Cable Extension', ru: 'Разгибания рук из-за головы на блоке', m: 'triceps', eq: 'cable', kind: 'wr', alias: ['overhead extension', 'french press', 'французский'] },
  { id: 'sa-pushdown', en: 'Single-Arm Pushdown', ru: 'Разгибание одной рукой на блоке', m: 'triceps', eq: 'cable', kind: 'wr', alias: ['pushdown', 'one arm', 'трицепс'] },
  { id: 'db-kickback', en: 'Triceps Kickback', ru: 'Разгибание руки с гантелью в наклоне', m: 'triceps', eq: 'dumbbell', kind: 'wr', alias: ['kickback', 'кикбэк'] },
  { id: 'dip-machine', en: 'Assisted Dip / Dip Machine', ru: 'Отжимания на брусьях в гравитроне', m: 'triceps', eq: 'machine', kind: 'wr', alias: ['dips', 'gravitron', 'брусья', 'гравитрон'] },
  { id: 'diamond-push-up', en: 'Diamond Push-Up', ru: 'Отжимания с узкой постановкой рук', m: 'triceps', eq: 'bodyweight', kind: 'reps', alias: ['pushup', 'close grip', 'алмазные', 'отжимания'] },
  { id: 'jm-press', en: 'JM Press', ru: 'Жим JM', m: 'triceps', eq: 'barbell', kind: 'wr', warn: 'shoulder', alias: ['jm'] },
  { id: 'db-lying-ext', en: 'Dumbbell Lying Extension', ru: 'Французский жим с гантелями лёжа', m: 'triceps', eq: 'dumbbell', kind: 'wr', alias: ['skull crusher', 'french press', 'французский'] },
  { id: 'machine-triceps-ext', en: 'Triceps Extension Machine', ru: 'Разгибания рук в тренажёре', m: 'triceps', eq: 'machine', kind: 'wr', alias: ['extension', 'трицепс'] },
  // ---- Forearms ----
  { id: 'reverse-wrist-curl', en: 'Reverse Wrist Curl', ru: 'Разгибания запястий обратным хватом', m: 'forearms', eq: 'dumbbell', kind: 'wr', alias: ['wrist', 'запястья'] },
  { id: 'btb-wrist-curl', en: 'Behind-the-Back Wrist Curl', ru: 'Сгибания запястий за спиной', m: 'forearms', eq: 'barbell', kind: 'wr', alias: ['wrist', 'запястья'] },
  { id: 'wrist-roller', en: 'Wrist Roller', ru: 'Наматывание ролика для кистей', m: 'forearms', eq: 'other', kind: 'reps', alias: ['roller', 'grip', 'ролик'] },
  { id: 'dead-hang', en: 'Dead Hang', ru: 'Вис на перекладине', m: 'forearms', eq: 'bodyweight', kind: 'time', alias: ['hang', 'grip', 'вис'] },
  { id: 'plate-pinch', en: 'Plate Pinch', ru: 'Удержание блинов щипковым хватом', m: 'forearms', eq: 'other', kind: 'time', alias: ['pinch', 'grip', 'хват'] },
  // ---- Quads ----
  { id: 'step-up', en: 'Dumbbell Step-Up', ru: 'Зашагивания на скамью с гантелями', m: 'quads', eq: 'dumbbell', kind: 'wr', alias: ['step up', 'зашагивания'] },
  { id: 'reverse-lunge', en: 'Reverse Lunge', ru: 'Выпады назад', m: 'quads', eq: 'dumbbell', kind: 'wr', alias: ['lunge', 'выпады'] },
  { id: 'smith-squat', en: 'Smith Machine Squat', ru: 'Приседания в машине Смита', m: 'quads', eq: 'smith', kind: 'wr', warn: 'back', alias: ['squat', 'смит', 'присед'] },
  { id: 'belt-squat', en: 'Belt Squat', ru: 'Приседания с поясом (белт-сквот)', m: 'quads', eq: 'machine', kind: 'wr', alias: ['squat', 'присед'] },
  { id: 'pendulum-squat', en: 'Pendulum Squat', ru: 'Маятниковые приседания в тренажёре', m: 'quads', eq: 'machine', kind: 'wr', alias: ['squat', 'присед'] },
  { id: 'sissy-squat', en: 'Sissy Squat', ru: 'Сисси-приседания', m: 'quads', eq: 'bodyweight', kind: 'reps', alias: ['sissy', 'присед'] },
  { id: 'sl-leg-press', en: 'Single-Leg Leg Press', ru: 'Жим одной ногой в тренажёре', m: 'quads', eq: 'machine', kind: 'wr', alias: ['leg press', 'жим ногами'] },
  { id: 'split-squat', en: 'Static Split Squat', ru: 'Сплит-приседания', m: 'quads', eq: 'dumbbell', kind: 'wr', alias: ['split squat', 'выпады'] },
  { id: 'hip-adduction', en: 'Hip Adduction Machine', ru: 'Сведение ног в тренажёре', m: 'quads', eq: 'machine', kind: 'wr', alias: ['adductor', 'adduction', 'inner thigh', 'сведение ног'] },
  // ---- Hamstrings ----
  { id: 'sl-rdl', en: 'Single-Leg Romanian Deadlift', ru: 'Румынская тяга на одной ноге', m: 'hamstrings', eq: 'dumbbell', kind: 'wr', alias: ['rdl', 'single leg', 'румынка'] },
  { id: 'cable-pull-through', en: 'Cable Pull-Through', ru: 'Протяжка на нижнем блоке', m: 'hamstrings', eq: 'cable', kind: 'wr', alias: ['pull through', 'протяжка'] },
  { id: 'ghr', en: 'Glute-Ham Raise', ru: 'Подъём корпуса на станке GHR', m: 'hamstrings', eq: 'bodyweight', kind: 'reps', alias: ['ghr', 'glute ham'] },
  { id: 'sldl', en: 'Stiff-Leg Deadlift', ru: 'Становая тяга на прямых ногах', m: 'hamstrings', eq: 'barbell', kind: 'wr', warn: 'back', alias: ['sldl', 'stiff leg', 'мёртвая тяга'] },
  { id: 'kb-swing', en: 'Kettlebell Swing', ru: 'Махи гирей', m: 'hamstrings', eq: 'kettlebell', kind: 'wr', alias: ['swing', 'kb', 'гиря'] },
  { id: 'standing-leg-curl', en: 'Standing Single-Leg Curl', ru: 'Сгибание ноги стоя в тренажёре', m: 'hamstrings', eq: 'machine', kind: 'wr', alias: ['leg curl', 'сгибание ног'] },
  { id: 'ball-leg-curl', en: 'Stability Ball Leg Curl', ru: 'Сгибания ног на фитболе', m: 'hamstrings', eq: 'other', kind: 'reps', alias: ['ball curl', 'leg curl', 'фитбол'] },
  // ---- Glutes ----
  { id: 'glute-bridge', en: 'Glute Bridge', ru: 'Ягодичный мостик', m: 'glutes', eq: 'bodyweight', kind: 'reps', alias: ['bridge', 'мостик'] },
  { id: 'sl-hip-thrust', en: 'Single-Leg Hip Thrust', ru: 'Ягодичный мост на одной ноге', m: 'glutes', eq: 'bodyweight', kind: 'reps', alias: ['hip thrust', 'single leg', 'мостик'] },
  { id: 'smith-hip-thrust', en: 'Smith Machine Hip Thrust', ru: 'Ягодичный мост в машине Смита', m: 'glutes', eq: 'smith', kind: 'wr', alias: ['hip thrust', 'смит', 'мостик'] },
  { id: 'reverse-hyper', en: 'Reverse Hyperextension', ru: 'Обратная гиперэкстензия', m: 'glutes', eq: 'machine', kind: 'wr', alias: ['reverse hyper', 'гиперэкстензия'] },
  { id: 'band-abduction', en: 'Banded Hip Abduction', ru: 'Отведение ног с резинкой', m: 'glutes', eq: 'band', kind: 'reps', alias: ['abduction', 'band', 'отведение', 'резинка'] },
  { id: 'cable-abduction', en: 'Cable Hip Abduction', ru: 'Отведение ноги в сторону на блоке', m: 'glutes', eq: 'cable', kind: 'wr', alias: ['abduction', 'отведение'] },
  // ---- Calves ----
  { id: 'donkey-calf', en: 'Donkey Calf Raise', ru: 'Подъём на носки в наклоне («ослик»)', m: 'calves', eq: 'machine', kind: 'wr', alias: ['calf', 'donkey', 'икры'] },
  { id: 'sl-calf-raise', en: 'Single-Leg Calf Raise', ru: 'Подъём на носок на одной ноге', m: 'calves', eq: 'dumbbell', kind: 'wr', alias: ['calf', 'икры'] },
  { id: 'smith-calf', en: 'Smith Machine Calf Raise', ru: 'Подъём на носки в машине Смита', m: 'calves', eq: 'smith', kind: 'wr', alias: ['calf', 'смит', 'икры'] },
  { id: 'tibialis-raise', en: 'Tibialis Raise', ru: 'Подъём носков стоя у стены', m: 'calves', eq: 'bodyweight', kind: 'reps', alias: ['tib raise', 'tibialis', 'голень'] },
  // ---- Core ----
  { id: 'lying-leg-raise', en: 'Lying Leg Raise (bench)', ru: 'Подъём прямых ног лёжа на скамье', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['leg raise', 'straight leg raise', 'подъём ног', 'пресс'] },
  { id: 'crunch', en: 'Crunch', ru: 'Скручивания лёжа', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['abs', 'скручивания', 'пресс'] },
  { id: 'machine-crunch', en: 'Ab Crunch Machine', ru: 'Скручивания в тренажёре для пресса', m: 'core', eq: 'machine', kind: 'wr', alias: ['abs', 'crunch machine', 'тренажёр для пресса', 'пресс'] },
  { id: 'rotary-torso', en: 'Rotary Torso Machine', ru: 'Повороты корпуса в тренажёре', m: 'core', eq: 'machine', kind: 'wr', alias: ['obliques', 'twist', 'косые', 'повороты'] },
  { id: 'captains-chair', en: "Captain's Chair Knee Raise", ru: 'Подъём коленей в упоре на локтях', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['knee raise', 'roman chair', 'подъём коленей', 'пресс'] },
  { id: 'decline-sit-up', en: 'Decline Sit-Up', ru: 'Подъёмы корпуса на наклонной скамье', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['sit-up', 'situp', 'пресс'] },
  { id: 'decline-crunch', en: 'Decline Crunch', ru: 'Скручивания на наклонной скамье', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['crunch', 'abs', 'пресс'] },
  { id: 'bicycle-crunch', en: 'Bicycle Crunch', ru: 'Велосипед (скручивания)', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['bicycle', 'obliques', 'велосипед', 'косые'] },
  { id: 'reverse-crunch', en: 'Reverse Crunch', ru: 'Обратные скручивания', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['abs', 'lower abs', 'пресс'] },
  { id: 'pallof-press', en: 'Pallof Press', ru: 'Жим Паллофа', m: 'core', eq: 'cable', kind: 'wr', alias: ['anti-rotation', 'паллоф'] },
  { id: 'hollow-hold', en: 'Hollow Body Hold', ru: 'Удержание «лодочка»', m: 'core', eq: 'bodyweight', kind: 'time', alias: ['hollow', 'лодочка'] },
  { id: 'bird-dog', en: 'Bird Dog', ru: 'Упражнение «птица-собака»', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['bird dog', 'птица-собака'] },
  { id: 'mountain-climber', en: 'Mountain Climber', ru: 'Скалолаз', m: 'core', eq: 'bodyweight', kind: 'time', alias: ['climber', 'скалолаз'] },
  { id: 'v-up', en: 'V-Up', ru: 'Складка (V-подъём)', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['v up', 'складка'] },
  { id: 'toes-to-bar', en: 'Toes-to-Bar', ru: 'Подъём ног к перекладине', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['t2b', 'ttb', 'подъём ног'] },
  { id: 'db-side-bend', en: 'Dumbbell Side Bend', ru: 'Наклоны в сторону с гантелью', m: 'core', eq: 'dumbbell', kind: 'wr', alias: ['side bend', 'obliques', 'косые'] },
  { id: 'roman-chair-side-bend', en: 'Roman Chair Side Bend', ru: 'Боковые наклоны на римском стуле', m: 'core', eq: 'bodyweight', kind: 'reps', alias: ['side bend', 'obliques', 'косые'] },
  { id: 'weighted-plank', en: 'Weighted Plank', ru: 'Планка с отягощением', m: 'core', eq: 'bodyweight', kind: 'time', alias: ['plank', 'планка'] },
  { id: 'landmine-rotation', en: 'Landmine Rotation', ru: 'Повороты корпуса с лендмайном', m: 'core', eq: 'barbell', kind: 'wr', alias: ['landmine', 'rotation', 'лендмайн', 'косые'] },
  { id: 'ball-crunch', en: 'Stability Ball Crunch', ru: 'Скручивания на фитболе', m: 'core', eq: 'other', kind: 'reps', alias: ['ball', 'abs', 'фитбол', 'пресс'] },
  // ---- Cardio ----
  { id: 'outdoor-walk', en: 'Outdoor Walk', ru: 'Ходьба на улице', m: 'cardio', eq: 'other', kind: 'time', alias: ['walk', 'ходьба', 'прогулка'] },
  { id: 'outdoor-run', en: 'Outdoor Run', ru: 'Бег на улице', m: 'cardio', eq: 'other', kind: 'time', alias: ['run', 'running', 'бег'] },
  { id: 'treadmill-run', en: 'Treadmill Run', ru: 'Бег на дорожке', m: 'cardio', eq: 'machine', kind: 'time', alias: ['run', 'treadmill', 'бег', 'дорожка'] },
  { id: 'incline-walk', en: 'Incline Treadmill Walk', ru: 'Ходьба в гору на дорожке', m: 'cardio', eq: 'machine', kind: 'time', alias: ['incline walk', 'treadmill', 'ходьба', 'дорожка'] },
  { id: 'jump-rope', en: 'Jump Rope', ru: 'Скакалка', m: 'cardio', eq: 'other', kind: 'time', alias: ['skipping', 'rope', 'скакалка'] },
  { id: 'air-bike', en: 'Air Bike', ru: 'Аэробайк', m: 'cardio', eq: 'machine', kind: 'time', alias: ['assault bike', 'echo bike', 'bike', 'аэробайк'] },
  { id: 'outdoor-cycling', en: 'Cycling (outdoor)', ru: 'Велосипед на улице', m: 'cardio', eq: 'other', kind: 'time', alias: ['bike', 'cycling', 'велосипед'] },
  { id: 'swimming', en: 'Swimming', ru: 'Плавание', m: 'cardio', eq: 'other', kind: 'time', alias: ['swim', 'pool', 'плавание', 'бассейн'] },
  { id: 'sled-push', en: 'Sled Push', ru: 'Толкание саней', m: 'cardio', eq: 'other', kind: 'time', alias: ['sled', 'prowler', 'сани'] },
  { id: 'skierg', en: 'SkiErg', ru: 'Лыжный тренажёр (SkiErg)', m: 'cardio', eq: 'machine', kind: 'time', alias: ['ski erg', 'лыжный'] },
];

// Built-in templates. The first two come from Artem's mass-gain program (full-body A/B).
// `since` = the SEED_REV that introduced a template; existing installs get it once (store.js upgradeSeeds).
// note_ru is the Russian note, used when the app language is Russian.
const SEED_REV = 2;

// Program templates renamed in rev 2, only if the user never renamed them.
const SEED_RENAMES = [
  { id: 'tpl-day-a', from: { name: 'Day A', name_ru: 'День A' } },
  { id: 'tpl-day-b', from: { name: 'Day B', name_ru: 'День B' } },
];

const SEED_TEMPLATES = [
  {
    id: 'tpl-day-a', name: 'Full body A · Push focus', name_ru: 'Всё тело A · акцент на жимы', seeded: true,
    items: [
      { exId: 'leg-press',      sets: 3, lo: 8,  hi: 12, note: 'Machine, back supported', note_ru: 'Тренажёр, спина прижата к спинке' },
      { exId: 'db-incline',     sets: 3, lo: 8,  hi: 12, note: 'Controlled load — protects shoulder', note_ru: 'Умеренный вес, бережёт плечо' },
      { exId: 'seated-row',     sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'lying-leg-curl', sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'lateral-raise',  sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'woodchopper',    sets: 3, lo: 10, hi: 15, note: 'Core', note_ru: 'Кор' },
    ],
  },
  {
    id: 'tpl-day-b', name: 'Full body B · Pull focus', name_ru: 'Всё тело B · акцент на тяги', seeded: true,
    items: [
      { exId: 'db-rdl',           sets: 3, lo: 8,  hi: 10, note: 'Strict form, no spinal rounding', note_ru: 'Строгая техника, спина не округляется' },
      { exId: 'lat-pulldown',     sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'db-shoulder',      sets: 3, lo: 8,  hi: 12, note: 'Controlled load', note_ru: 'Умеренный вес' },
      { exId: 'cs-row',           sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'leg-extension',    sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'hanging-leg-raise',sets: 3, lo: 8,  hi: 15, note: 'Core', note_ru: 'Кор' },
    ],
  },
  {
    id: 'tpl-upper', since: 2, name: 'Upper body · Chest, back, shoulders', name_ru: 'Верх тела · грудь, спина, плечи', seeded: false,
    items: [
      { exId: 'machine-press',    sets: 3, lo: 8,  hi: 12, note: 'Handles at mid-chest', note_ru: 'Рукояти на уровне середины груди' },
      { exId: 'lat-pulldown',     sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'db-shoulder',      sets: 3, lo: 8,  hi: 12, note: 'Controlled load', note_ru: 'Умеренный вес' },
      { exId: 'seated-row',       sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'reverse-pec-deck', sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'hammer-curl',      sets: 2, lo: 10, hi: 12, note: '' },
      { exId: 'rope-pushdown',    sets: 2, lo: 10, hi: 12, note: '' },
    ],
  },
  {
    id: 'tpl-lower', since: 2, name: 'Lower body · Legs & glutes', name_ru: 'Низ тела · ноги и ягодицы', seeded: false,
    items: [
      { exId: 'hack-squat',      sets: 3, lo: 8,  hi: 12, note: 'Back supported', note_ru: 'Спина прижата к спинке' },
      { exId: 'db-rdl',          sets: 3, lo: 8,  hi: 10, note: 'Strict form, no spinal rounding', note_ru: 'Строгая техника, спина не округляется' },
      { exId: 'bulgarian',       sets: 3, lo: 8,  hi: 10, note: 'Each leg', note_ru: 'На каждую ногу' },
      { exId: 'seated-leg-curl', sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'hip-thrust-mach', sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'standing-calf',   sets: 3, lo: 10, hi: 15, note: '' },
    ],
  },
  {
    id: 'tpl-push', since: 2, name: 'Push · Chest, shoulders, triceps', name_ru: 'Жимы · грудь, плечи, трицепс', seeded: false,
    items: [
      { exId: 'db-incline',       sets: 3, lo: 8,  hi: 12, note: 'Controlled load, protects the shoulder', note_ru: 'Умеренный вес, бережёт плечо' },
      { exId: 'machine-press',    sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'machine-shoulder', sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'low-cable-fly',    sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'lateral-raise',    sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'oh-cable-ext',     sets: 3, lo: 10, hi: 12, note: '' },
    ],
  },
  {
    id: 'tpl-pull', since: 2, name: 'Pull · Back, rear delts, biceps', name_ru: 'Тяги · спина, задняя дельта, бицепс', seeded: false,
    items: [
      { exId: 'lat-pulldown',    sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'cs-row',          sets: 3, lo: 8,  hi: 12, note: '' },
      { exId: 'sa-lat-pulldown', sets: 3, lo: 10, hi: 12, note: 'Each arm', note_ru: 'На каждую руку' },
      { exId: 'face-pull',       sets: 3, lo: 12, hi: 15, note: '' },
      { exId: 'back-extension',  sets: 3, lo: 10, hi: 15, note: 'Neutral spine, no swinging', note_ru: 'Спина прямая, без рывков' },
      { exId: 'incline-curl',    sets: 3, lo: 10, hi: 12, note: '' },
    ],
  },
  {
    id: 'tpl-core', since: 2, name: 'Core · Abs & obliques', name_ru: 'Кор · пресс и косые', seeded: false,
    items: [
      { exId: 'machine-crunch',  sets: 3, lo: 10, hi: 15, note: '' },
      { exId: 'lying-leg-raise', sets: 3, lo: 10, hi: 15, note: '' },
      { exId: 'captains-chair',  sets: 3, lo: 10, hi: 15, note: '' },
      { exId: 'rotary-torso',    sets: 3, lo: 12, hi: 15, note: 'Each side', note_ru: 'На каждую сторону' },
      { exId: 'pallof-press',    sets: 3, lo: 10, hi: 12, note: 'Each side', note_ru: 'На каждую сторону' },
      { exId: 'plank',           sets: 3, lo: null, hi: null, note: '30–60 s', note_ru: '30–60 с' },
    ],
  },
  {
    id: 'tpl-express', since: 2, name: 'Express full body · 30–40 min', name_ru: 'Экспресс · всё тело за 30–40 мин', seeded: false,
    items: [
      { exId: 'leg-press',      sets: 2, lo: 8,  hi: 12, note: 'A short session beats a skipped one', note_ru: 'Короткая тренировка лучше пропуска' },
      { exId: 'machine-press',  sets: 2, lo: 8,  hi: 12, note: '' },
      { exId: 'lat-pulldown',   sets: 2, lo: 8,  hi: 12, note: '' },
      { exId: 'db-rdl',         sets: 2, lo: 8,  hi: 10, note: '' },
      { exId: 'machine-crunch', sets: 2, lo: 10, hi: 15, note: '' },
    ],
  },
  {
    id: 'tpl-conditioning', since: 2, name: 'Conditioning · Cardio & core', name_ru: 'Выносливость · кардио и кор', seeded: false,
    items: [
      { exId: 'rowing',           sets: 1, lo: null, hi: null, note: 'Easy warm-up, 8–10 min', note_ru: 'Лёгкая разминка, 8–10 мин' },
      { exId: 'kb-swing',         sets: 3, lo: 15, hi: 20, note: 'Hinge from the hips', note_ru: 'Движение из таза' },
      { exId: 'step-up',          sets: 3, lo: 10, hi: 12, note: 'Each leg', note_ru: 'На каждую ногу' },
      { exId: 'mountain-climber', sets: 3, lo: null, hi: null, note: '30–40 s', note_ru: '30–40 с' },
      { exId: 'dead-bug',         sets: 3, lo: 10, hi: 12, note: '' },
      { exId: 'incline-walk',     sets: 1, lo: null, hi: null, note: '15–20 min', note_ru: '15–20 мин' },
    ],
  },
];

const I18N = {
  en: {
    app: 'FREILIFT',
    tab_home: 'Today', tab_history: 'History', tab_exercises: 'Exercises', tab_stats: 'Stats', tab_body: 'Body',
    settings: 'Settings',
    start_empty: 'Start empty workout', start_from: 'Start from template',
    resume: 'Resume workout', in_progress: 'Workout in progress',
    no_workouts: 'No workouts logged yet.',
    last_workout: 'Last workout', this_week: 'This week', sessions: 'sessions',
    add_exercise: 'Add exercise', add_set: 'Add set', finish: 'Finish', discard: 'Discard',
    weight: 'Weight', reps: 'Reps', time: 'Time', set: 'Set', prev: 'Prev', rir: 'RIR',
    notes: 'Notes', note_ph: 'Notes…', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
    close: 'Close', done: 'Done', all: 'All', search: 'Search…',
    new_exercise: 'New exercise', name: 'Name', muscle: 'Muscle group', equipment: 'Equipment',
    type: 'Tracking type', type_wr: 'Weight × reps', type_reps: 'Reps only', type_time: 'Duration',
    description: 'Description',
    templates: 'Templates', save_as_template: 'Save as template', template_name: 'Template name',
    no_templates: 'No templates yet.',
    workout_name: 'Workout name',
    volume: 'Volume', total_volume: 'Total volume', workouts: 'Workouts', streak: 'Streak', weeks: 'wks',
    best_set: 'Best set', est_1rm: 'Est. 1RM', per_exercise: 'Per exercise', overall: 'Overall',
    last_12_weeks: 'Volume — last 12 weeks', muscle_split: 'Muscle split — last 30 days',
    avg_per_week: 'Avg / week', duration: 'Duration', min: 'min',
    body_weight: 'Body weight', log_weight: 'Log weight', measurements: 'Measurements',
    waist: 'Waist', chest_m: 'Chest', arm: 'Arm', thigh: 'Thigh', neck: 'Neck',
    goal: 'Goal', start_w: 'Start', current: 'Current', to_go: 'To go', trend7: '7-day avg',
    weekly_change: 'Weekly change', target_rate: 'target 0.18–0.20 kg/wk',
    lang: 'Language', theme: 'Theme', dark: 'Dark', light: 'Light',
    rest_timer: 'Rest timer', rest_default: 'Default rest', vibrate: 'Sound / vibration on finish',
    repeat: 'Repeat workout', exercises_n: 'exercises',
    front: 'Front', back_view: 'Back', primary: 'Primary', secondary: 'Also works',
    how_to: 'How to perform (YouTube)', info: 'How to / info',
    new_template: 'New template', edit_template: 'Edit template', duplicate: 'Duplicate',
    sets_target: 'Sets', rep_range: 'Reps', tpl_empty: 'Add exercises to this template.',
    tpl_name_required: 'Give the template a name.', new: 'New',
    progression: 'Progression hints', plate_calc: 'Plate calculator', program_warn: 'Program warnings',
    bar_weight: 'Bar weight', data: 'Data', export: 'Export backup (JSON)', import: 'Import backup',
    wipe: 'Erase all data', wipe_confirm: 'Erase everything? This cannot be undone.',
    last_backup: 'Last backup', never: 'never', days_ago: 'd ago', today: 'today',
    backup_due: 'No backup in {n} days — export one.', backup_never: 'No backup yet. Export one.',
    progression_hit: 'Top of rep range hit on all sets → add weight next session.',
    warn_back: 'Your program flags this: axial spinal load. Prefer leg press / hack squat / machine squat.',
    warn_shoulder: 'Your program flags this: shoulder risk. Prefer dumbbell press with moderate load.',
    plates_per_side: 'Per side', target_weight: 'Target weight',
    empty_stats: 'Log a few workouts to see stats.',
    confirm_delete: 'Delete this?', custom: 'Custom', seeded_program: 'From your program',
    kg: 'kg', cm: 'cm', sets_short: 'sets', imported: 'Backup imported.', import_failed: 'Import failed — invalid file.',
    exercise_exists: 'An exercise with this name already exists.',
    pick_template: 'Pick a template', quick_add: 'Quick add', history_for: 'History',
    no_history_ex: 'No history for this exercise yet.',
    week: 'Week', total: 'Total', sets_done: 'sets', reps_total: 'reps',
    finish_confirm: 'Finish and save this workout?', discard_confirm: 'Discard this workout? Nothing will be saved.',
    empty_workout: 'Add at least one set before finishing.',
    rest: 'Rest', skip: 'Skip', add30: '+30s',
    program_note: 'Program', trend: 'Trend',
    log_set: 'Log set {n}', set_n: 'Set {n}', last: 'Last', on_target: 'On target', warmup: 'Warm-up',
    unit_reps: 'reps', unit_sec: 'sec', unit_pluskg: '+kg',
    hint_steps: 'Steps of {n}', hint_hold_repeat: 'hold to repeat', hint_type: 'tap a number to type',
    set_deleted: 'Set {n} deleted', undo: 'Undo', delete_now: 'Delete now',
    mark_warm: 'Mark as warm-up', mark_working: 'Mark as working set', edit_set: 'Edit this set', delete_set: 'Delete set',
    exercise_options: 'Exercise options', move_up: 'Move up', move_down: 'Move down', search_ex: 'Search · RDL, OHP, жим',
    this_session: 'This session', discard_workout: 'Discard workout',
    reps_lo: 'Reps from', reps_hi: 'Reps to',
    hidden_ex: 'Hidden exercises', restore: 'Restore', w_step: 'Weight step',
    vol_12w: 'Volume · 12 weeks', tonnes: 'tonnes', split_30: 'Muscle split · 30 days',
    empty_log_t: 'An empty session.', empty_log_s: 'Add the first exercise to start logging.',
    empty_hist_t: 'Every finished workout lands here.', empty_hist_s: 'Start one from Today. It appears here after you tap Finish.',
    empty_stats_t: 'Trends appear after a few sessions.', empty_stats_s: 'Log and finish a workout to start the charts.',
    empty_ex_t: 'Nothing matches that search.', empty_ex_s: 'Try a short name like RDL or жим, or add it as a new exercise.',
    empty_tpl_t: 'No templates yet.', empty_tpl_s: 'Create one and start a whole workout with one tap.',
    empty_body_t: 'No weigh-ins yet.', empty_body_s: 'Log your weight above. The 7-day trend starts after two entries.',
    empty_exhist_s: 'It shows up here after you log it once.',
    plates_left: 'Not exact with your plates: {n} kg left over',
    version: 'FREILIFT · v4 · data stays on this device',
    date: 'Date',
    all_templates: 'All templates', tpl_one: '{n} template', tpl_many: '{n} templates',
    sess_one: '{n} session', sess_many: '{n} sessions', exn_one: '{n} exercise', exn_many: '{n} exercises',
    /* v4 */
    tab_workout: 'Workout', ex_of: 'Exercise {n} of {m}', more: 'More', group: 'Group',
    switch_ex: 'Switch exercise', session_menu: 'This workout', up_next: 'Up next',
    finish_workout: 'Finish workout', all_done_t: 'Every set is logged.', all_done_s: 'Finish the workout to save it.',
    sets_of: '{n} of {m} sets', set_of: 'Set {n} of {m}', open_stats: 'Stats and charts', open_body: 'Body weight',
    last_one: 'Last',
    /* v5: information architecture pass */
    tab_progress: 'Progress', next_in_program: 'Next in your program', start_day: 'Start {name}',
    train_else: 'Train something else', empty_workout: 'Empty workout', start_a_workout: 'Start a workout',
    and_more: 'and {n} more', no_exercises_yet: 'No exercises yet',
    in_progress_hint: 'One workout at a time. Templates and the rest of Today come back once you finish this one.',
    setsl_one: '{n} set logged', setsl_many: '{n} sets logged', started_ago: 'started {n} min ago', started_ago_hm: 'started {h} h {m} min ago',
    days_ago_short: '{n} days ago', yesterday: 'yesterday',
    workouts_week: 'Workouts this week', week_streak: 'Week streak',
    per_exercise_row: 'Per exercise', split_row: 'Muscle split', kg_today: 'kg today', since: 'since {month}',
    vol_up: 'Up {n}% on the four weeks before', vol_down: 'Down {n}% on the four weeks before',
    vol_steady: 'Steady over the last eight weeks', vol_up_much: 'Well up on the four weeks before', back: 'Back',
    /* v6: logger rebuild */
    add_weight: 'Add weight', t_start: 'Start', t_pause: 'Pause', t_resume: 'Resume', t_log: 'Log',
    last_time: 'Last time', filter: 'Filter', clear: 'Clear',
    shown_one: 'Show {n} exercise', shown_many: 'Show {n} exercises',
    reopen_workout: 'Reopen workout', discard_n: 'Discard this workout? {n} logged sets are lost.',
    no_sets_logged: 'Log at least one set first.', workout: 'Workout',
    edit_set_title: 'Set {n}', remove_exercise: 'Remove exercise',
  },
  ru: {
    app: 'FREILIFT',
    tab_home: 'Сегодня', tab_history: 'История', tab_exercises: 'Упражнения', tab_stats: 'Статистика', tab_body: 'Тело',
    settings: 'Настройки',
    start_empty: 'Начать пустую тренировку', start_from: 'Начать по шаблону',
    resume: 'Продолжить тренировку', in_progress: 'Тренировка идёт',
    no_workouts: 'Пока нет тренировок.',
    last_workout: 'Последняя тренировка', this_week: 'На этой неделе', sessions: 'тренировок',
    add_exercise: 'Добавить упражнение', add_set: 'Добавить подход', finish: 'Завершить', discard: 'Отменить',
    weight: 'Вес', reps: 'Повт.', time: 'Время', set: 'Подход', prev: 'Пред.', rir: 'RIR',
    notes: 'Заметки', note_ph: 'Заметки…', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить',
    close: 'Закрыть', done: 'Готово', all: 'Все', search: 'Поиск…',
    new_exercise: 'Новое упражнение', name: 'Название', muscle: 'Мышечная группа', equipment: 'Оборудование',
    type: 'Тип учёта', type_wr: 'Вес × повторы', type_reps: 'Только повторы', type_time: 'Длительность',
    description: 'Описание',
    templates: 'Шаблоны', save_as_template: 'Сохранить как шаблон', template_name: 'Название шаблона',
    no_templates: 'Шаблонов пока нет.',
    workout_name: 'Название тренировки',
    volume: 'Объём', total_volume: 'Общий объём', workouts: 'Тренировки', streak: 'Серия', weeks: 'нед.',
    best_set: 'Лучший подход', est_1rm: 'Расч. 1ПМ', per_exercise: 'По упражнению', overall: 'Общая',
    last_12_weeks: 'Объём — последние 12 недель', muscle_split: 'По группам — 30 дней',
    avg_per_week: 'В среднем / нед.', duration: 'Длительность', min: 'мин',
    body_weight: 'Вес тела', log_weight: 'Записать вес', measurements: 'Замеры',
    waist: 'Талия', chest_m: 'Грудь', arm: 'Рука', thigh: 'Бедро', neck: 'Шея',
    goal: 'Цель', start_w: 'Старт', current: 'Сейчас', to_go: 'Осталось', trend7: 'Среднее за 7 дней',
    weekly_change: 'Изменение за неделю', target_rate: 'цель 0,18–0,20 кг/нед.',
    lang: 'Язык', theme: 'Тема', dark: 'Тёмная', light: 'Светлая',
    rest_timer: 'Таймер отдыха', rest_default: 'Отдых по умолчанию', vibrate: 'Звук / вибрация по окончании',
    repeat: 'Повторить тренировку', exercises_n: 'упражнений',
    front: 'Спереди', back_view: 'Сзади', primary: 'Основная', secondary: 'Дополнительно',
    how_to: 'Как выполнять (YouTube)', info: 'Техника / инфо',
    new_template: 'Новый шаблон', edit_template: 'Изменить шаблон', duplicate: 'Дублировать',
    sets_target: 'Подходы', rep_range: 'Повторы', tpl_empty: 'Добавьте упражнения в шаблон.',
    tpl_name_required: 'Укажите название шаблона.', new: 'Новый',
    progression: 'Подсказки прогрессии', plate_calc: 'Калькулятор блинов', program_warn: 'Предупреждения программы',
    bar_weight: 'Вес грифа', data: 'Данные', export: 'Экспорт резервной копии (JSON)', import: 'Импорт копии',
    wipe: 'Удалить все данные', wipe_confirm: 'Удалить всё? Это необратимо.',
    last_backup: 'Последняя копия', never: 'никогда', days_ago: ' дн. назад', today: 'сегодня',
    backup_due: 'Копии не было {n} дн. — сделайте экспорт.', backup_never: 'Резервной копии ещё нет. Сделайте экспорт.',
    progression_hit: 'Верх диапазона взят во всех подходах → добавьте вес в следующий раз.',
    warn_back: 'Программа не рекомендует: осевая нагрузка на позвоночник. Лучше жим ногами / гакк / присед в тренажёре.',
    warn_shoulder: 'Программа не рекомендует: риск для плеча. Лучше жим гантелей с умеренным весом.',
    plates_per_side: 'На сторону', target_weight: 'Целевой вес',
    empty_stats: 'Запишите несколько тренировок, чтобы увидеть статистику.',
    confirm_delete: 'Удалить?', custom: 'Своё', seeded_program: 'Из вашей программы',
    kg: 'кг', cm: 'см', sets_short: 'подх.', imported: 'Копия загружена.', import_failed: 'Ошибка импорта — неверный файл.',
    exercise_exists: 'Упражнение с таким названием уже есть.',
    pick_template: 'Выберите шаблон', quick_add: 'Быстрое добавление', history_for: 'История',
    no_history_ex: 'Пока нет истории по этому упражнению.',
    week: 'Неделя', total: 'Всего', sets_done: 'подх.', reps_total: 'повт.',
    finish_confirm: 'Завершить и сохранить тренировку?', discard_confirm: 'Отменить тренировку? Ничего не сохранится.',
    empty_workout: 'Добавьте хотя бы один подход перед завершением.',
    rest: 'Отдых', skip: 'Пропустить', add30: '+30 с',
    program_note: 'Программа', trend: 'Тренд',
    log_set: 'Записать подход {n}', set_n: 'Подход {n}', last: 'Прошлый', on_target: 'В диапазоне', warmup: 'Разминка',
    unit_reps: 'повт.', unit_sec: 'сек', unit_pluskg: '+кг',
    hint_steps: 'Шаг {n}', hint_hold_repeat: 'удерживайте для повтора', hint_type: 'нажмите на число для ввода',
    set_deleted: 'Подход {n} удалён', undo: 'Вернуть', delete_now: 'Удалить сразу',
    mark_warm: 'Отметить как разминку', mark_working: 'Сделать рабочим подходом', edit_set: 'Изменить подход', delete_set: 'Удалить подход',
    exercise_options: 'Действия с упражнением', move_up: 'Выше', move_down: 'Ниже', search_ex: 'Поиск · RDL, OHP, жим',
    this_session: 'Эта тренировка', discard_workout: 'Отменить тренировку',
    reps_lo: 'Повт. от', reps_hi: 'Повт. до',
    hidden_ex: 'Скрытые упражнения', restore: 'Вернуть', w_step: 'Шаг веса',
    vol_12w: 'Объём · 12 недель', tonnes: 'тонн', split_30: 'По группам · 30 дней',
    empty_log_t: 'Пустая тренировка.', empty_log_s: 'Добавьте первое упражнение, чтобы начать запись.',
    empty_hist_t: 'Здесь появятся завершённые тренировки.', empty_hist_s: 'Начните тренировку на вкладке «Сегодня». Она появится здесь после «Завершить».',
    empty_stats_t: 'Тренды появятся после нескольких тренировок.', empty_stats_s: 'Запишите и завершите тренировку, чтобы начать графики.',
    empty_ex_t: 'Ничего не найдено.', empty_ex_s: 'Попробуйте короткое название, например RDL или жим, или добавьте новое упражнение.',
    empty_tpl_t: 'Шаблонов пока нет.', empty_tpl_s: 'Создайте шаблон и начинайте всю тренировку одним нажатием.',
    empty_body_t: 'Пока нет записей веса.', empty_body_s: 'Запишите вес выше. Тренд за 7 дней появится после двух записей.',
    empty_exhist_s: 'История появится после первой записи.',
    plates_left: 'Не набирается точно: остаётся {n} кг',
    version: 'FREILIFT · v4 · данные хранятся только на этом устройстве',
    date: 'Дата',
    all_templates: 'Все шаблоны', tpl_one: '{n} шаблон', tpl_few: '{n} шаблона', tpl_many: '{n} шаблонов',
    sess_one: '{n} тренировка', sess_few: '{n} тренировки', sess_many: '{n} тренировок', exn_one: '{n} упражнение', exn_few: '{n} упражнения', exn_many: '{n} упражнений',
    /* v4 */
    tab_workout: 'Тренировка', ex_of: 'Упражнение {n} из {m}', more: 'Ещё', group: 'Группа',
    switch_ex: 'Другое упражнение', session_menu: 'Эта тренировка', up_next: 'Далее',
    finish_workout: 'Завершить тренировку', all_done_t: 'Все подходы записаны.', all_done_s: 'Завершите тренировку, чтобы сохранить её.',
    sets_of: '{n} из {m} подходов', set_of: 'Подход {n} из {m}', open_stats: 'Статистика и графики', open_body: 'Вес тела',
    last_one: 'Последняя',
    /* v5: information architecture pass */
    tab_progress: 'Прогресс', next_in_program: 'Следующая в программе', start_day: 'Начать: {name}',
    train_else: 'Другая тренировка', empty_workout: 'Пустая тренировка', start_a_workout: 'Начать тренировку',
    and_more: 'и ещё {n}', no_exercises_yet: 'Пока нет упражнений',
    in_progress_hint: 'Одна тренировка за раз. Шаблоны и остальное на «Сегодня» вернутся, когда вы закончите.',
    setsl_one: 'записан {n} подход', setsl_few: 'записано {n} подхода', setsl_many: 'записано {n} подходов', started_ago: 'начата {n} мин назад', started_ago_hm: 'начата {h} ч {m} мин назад',
    days_ago_short: '{n} дн. назад', yesterday: 'вчера',
    workouts_week: 'Тренировок на этой неделе', week_streak: 'Серия недель',
    per_exercise_row: 'По упражнению', split_row: 'По группам мышц', kg_today: 'кг сегодня', since: 'с {month}',
    vol_up: 'Рост {n}% к предыдущим четырём неделям', vol_down: 'Снижение {n}% к предыдущим четырём неделям',
    vol_steady: 'Без изменений за последние восемь недель', vol_up_much: 'Заметно выше, чем четыре недели назад', back: 'Назад',
    /* v6: logger rebuild */
    add_weight: 'Добавить вес', t_start: 'Старт', t_pause: 'Пауза', t_resume: 'Дальше', t_log: 'Записать',
    last_time: 'Прошлый раз', filter: 'Фильтр', clear: 'Сбросить',
    shown_one: 'Показать {n} упражнение', shown_few: 'Показать {n} упражнения', shown_many: 'Показать {n} упражнений',
    reopen_workout: 'Вернуться к тренировке', discard_n: 'Удалить тренировку? Потеряется подходов: {n}.',
    no_sets_logged: 'Сначала запишите хотя бы один подход.', workout: 'Тренировка',
    edit_set_title: 'Подход {n}', remove_exercise: 'Убрать упражнение',
  },
};
