/* GymLog — per-exercise how-to notes + secondary muscles
   sec: secondary muscle groups (primary comes from the exercise's own `m` field) */

const EX_INFO = {
  /* ---------- Chest ---------- */
  'bb-bench': { sec: ['triceps', 'shoulders'], en: 'Lie flat, shoulder blades pulled back and down, feet planted. Lower the bar to mid-chest under control and press without letting the elbows flare past ~60°.', ru: 'Лягте на скамью, лопатки сведены и опущены, стопы упёрты в пол. Опускайте штангу к середине груди подконтрольно и жмите, не разводя локти шире ~60°.' },
  'bb-incline': { sec: ['triceps', 'shoulders'], en: 'Bench at 30°, not steeper — higher angles shift the load onto the front delts. Touch the upper chest, press in a slight arc back over the shoulders.', ru: 'Наклон скамьи 30°, не круче — больший угол переносит нагрузку на передние дельты. Касайтесь верха груди, жмите по небольшой дуге назад, к плечам.' },
  'db-bench': { sec: ['triceps', 'shoulders'], en: 'Dumbbells allow a natural wrist path and a deeper stretch than a bar. Lower until the elbows are just below the torso, press without clanging the bells together.', ru: 'Гантели дают естественную траекторию кисти и большую растяжку, чем штанга. Опускайте, пока локти не окажутся чуть ниже корпуса, вверху не стучите гантелями друг о друга.' },
  'db-incline': { sec: ['triceps', 'shoulders'], en: 'Bench at 30°. Keep the elbows slightly tucked and stop the descent when you feel the stretch — no forcing depth at the shoulder joint.', ru: 'Наклон 30°. Локти слегка прижаты, опускание останавливайте на ощущении растяжения — не продавливайте плечевой сустав ради глубины.' },
  'machine-press': { sec: ['triceps', 'shoulders'], en: 'Set the seat so the handles sit at mid-chest height. The fixed path makes this the safest heavy pressing option for a cranky shoulder.', ru: 'Отрегулируйте сиденье так, чтобы рукояти были на уровне середины груди. Фиксированная траектория делает это самым безопасным тяжёлым жимом для проблемного плеча.' },
  'pec-deck': { sec: ['shoulders'], en: 'Isolation for the chest — elbows slightly bent and locked at that angle throughout. Squeeze for a beat at the point of full contraction.', ru: 'Изоляция на грудь — локти чуть согнуты и зафиксированы в этом положении. В точке максимального сведения задержитесь на секунду.' },
  'cable-fly': { sec: ['shoulders'], en: 'Constant tension the whole range, unlike dumbbell flyes. Step forward slightly, lead with the elbows and bring the hands together in front of the sternum.', ru: 'Постоянное натяжение по всей амплитуде, в отличие от разводок с гантелями. Сделайте небольшой шаг вперёд, ведите движение локтями и сводите руки перед грудиной.' },
  'push-up': { sec: ['triceps', 'shoulders', 'core'], en: 'Body in one line from head to heels, hands slightly wider than the shoulders. Add load with a plate on the back or elevate the feet once bodyweight is easy.', ru: 'Тело в одну линию от головы до пяток, руки чуть шире плеч. Когда свой вес становится лёгким, добавьте блин на спину или поднимите ноги на возвышение.' },
  'chest-dip': { sec: ['triceps', 'shoulders'], en: 'Lean the torso forward ~30° to bias the chest. Stop when the upper arms reach parallel — going deeper stresses the shoulder capsule.', ru: 'Наклоните корпус вперёд примерно на 30°, чтобы нагрузить грудь. Останавливайтесь, когда плечо доходит до параллели — глубже нагружается капсула плечевого сустава.' },

  /* ---------- Back ---------- */
  'lat-pulldown': { sec: ['biceps', 'forearms'], en: 'Grip slightly wider than the shoulders. Pull the bar to the collarbone by driving the elbows down and back, chest up, no big backward lean.', ru: 'Хват чуть шире плеч. Тяните рукоять к ключицам, направляя локти вниз и назад, грудь раскрыта, без сильного отклонения корпуса назад.' },
  'pull-up': { sec: ['biceps', 'forearms', 'core'], en: 'Start from a dead hang, pull until the chin clears the bar, lower under control. Use a band or the assisted machine if you can\'t get 5 clean reps.', ru: 'Начинайте из полного виса, тянитесь, пока подбородок не окажется выше перекладины, опускайтесь подконтрольно. Если не выходит 5 чистых повторов — резина или гравитрон.' },
  'assisted-pullup': { sec: ['biceps', 'forearms'], en: 'The counterweight reduces your effective bodyweight, so a higher number on the stack means more help. Reduce the assistance as you get stronger.', ru: 'Противовес уменьшает ваш рабочий вес: чем больше вес на стеке, тем сильнее помощь. По мере прогресса уменьшайте помощь.' },
  'seated-row': { sec: ['biceps', 'forearms'], en: 'Chest tall, pull the handle to the navel, squeeze the shoulder blades together. Keep the lower back still — no rocking to move the weight.', ru: 'Грудь раскрыта, тяните рукоять к животу, сводя лопатки. Поясница неподвижна — не раскачивайтесь, чтобы сдвинуть вес.' },
  'cs-row': { sec: ['biceps', 'forearms'], en: 'The chest pad takes the lower back out of the movement — a good rowing option when the spine needs protecting. Pull elbows past the torso, pause, control the return.', ru: 'Упор в грудь выключает поясницу — хороший вариант тяги, когда нужно беречь спину. Проводите локти за корпус, пауза, подконтрольный возврат.' },
  'bb-row': { sec: ['biceps', 'forearms', 'hamstrings'], en: 'Hinge to ~45°, brace hard, pull to the lower ribs. The unsupported spine takes real load here — go lighter or pick a chest-supported row if your back is sensitive.', ru: 'Наклон около 45°, жёсткое напряжение корпуса, тяга к нижним рёбрам. Позвоночник без опоры реально нагружен — при чувствительной спине берите меньше веса или тягу с упором в грудь.' },
  'db-row': { sec: ['biceps', 'forearms'], en: 'One knee and hand on the bench, back flat. Pull the dumbbell to the hip, not to the shoulder, and let the shoulder blade travel at the bottom.', ru: 'Колено и рука на скамье, спина ровная. Тяните гантель к бедру, а не к плечу, внизу давайте лопатке уйти вперёд.' },
  't-bar-row': { sec: ['biceps', 'forearms'], en: 'Heavy mid-back work. Chest supported if the machine allows — the free-standing version loads the lower back the same way a barbell row does.', ru: 'Тяжёлая работа на середину спины. Если тренажёр позволяет — с упором в грудь; свободный вариант грузит поясницу так же, как тяга штанги.' },
  'sa-pulldown': { sec: [], en: 'Arms nearly straight the whole time — the movement happens at the shoulder, not the elbow. Isolates the lats without involving the biceps.', ru: 'Руки почти прямые всё движение — работает плечевой сустав, а не локтевой. Изолирует широчайшие, не подключая бицепс.' },
  'deadlift': { sec: ['hamstrings', 'glutes', 'forearms', 'core'], en: 'Maximum axial load of any lift. Bar over mid-foot, brace, push the floor away with a neutral spine. Skip it entirely if your back isn\'t cleared for loading.', ru: 'Максимальная осевая нагрузка среди всех упражнений. Гриф над серединой стопы, жёсткий корпус, отталкивайтесь от пола с нейтральной спиной. При непролеченной спине — не делать вообще.' },
  'rack-pull': { sec: ['glutes', 'forearms'], en: 'Deadlift from pins at or just below the knee — shorter range, less hip flexion, still heavy spinal loading.', ru: 'Становая с плинтов на уровне колена или чуть ниже — короче амплитуда, меньше сгибание в тазобедренном, но осевая нагрузка на позвоночник сохраняется.' },
  'db-shrug': { sec: ['forearms'], en: 'Straight up and down — rolling the shoulders adds nothing. Hold the top position for a second on each rep.', ru: 'Строго вверх-вниз — вращать плечами бессмысленно. В верхней точке задержка на секунду.' },

  /* ---------- Shoulders ---------- */
  'db-shoulder': { sec: ['triceps'], en: 'Seated with back support. Press from ear height to lockout without shrugging; dumbbells let the shoulders rotate naturally, unlike a barbell.', ru: 'Сидя с опорой на спинку. Жмите от уровня ушей до выпрямления рук без пожимания плечами; гантели, в отличие от штанги, позволяют плечу вращаться естественно.' },
  'bb-ohp': { sec: ['triceps', 'core'], en: 'The bar has to travel around the head, which forces shoulder extension and internal rotation — the position most likely to aggravate an irritated shoulder.', ru: 'Гриф вынужден идти вокруг головы, что требует разгибания и внутренней ротации плеча — самое рискованное положение для раздражённого плечевого сустава.' },
  'machine-shoulder': { sec: ['triceps'], en: 'The fixed path removes the balance demand and lets you push closer to failure safely. Set the seat so the handles start at shoulder height.', ru: 'Фиксированная траектория снимает задачу стабилизации и позволяет безопаснее работать до отказа. Настройте сиденье так, чтобы рукояти были на уровне плеч.' },
  'lateral-raise': { sec: [], en: 'Lead with the elbows, thumbs level or slightly down, stop at shoulder height. Light weight and strict form beat heavy swinging here.', ru: 'Ведите движение локтями, большие пальцы на уровне мизинцев или чуть ниже, останавливайтесь на уровне плеч. Малый вес и строгая техника лучше, чем тяжёлые махи с раскачкой.' },
  'cable-lateral': { sec: [], en: 'Same movement as the dumbbell version but with tension at the bottom, where dumbbells give none. Cable behind the back, one arm at a time.', ru: 'То же движение, что с гантелями, но с нагрузкой в нижней точке, где гантели её не дают. Трос за спиной, работайте по одной руке.' },
  'rear-delt-fly': { sec: ['back'], en: 'Bent over or chest-supported, elbows slightly bent, sweep the arms out and back. Directly balances all the pressing volume — worth including every week.', ru: 'В наклоне или с упором в скамью, локти слегка согнуты, разводите руки в стороны и назад. Прямо компенсирует объём жимов — стоит делать каждую неделю.' },
  'face-pull': { sec: ['back'], en: 'Rope at eye height, pull towards the forehead while rotating the hands outward. The best single exercise for shoulder health and posture.', ru: 'Канат на уровне глаз, тяните ко лбу, разворачивая кисти наружу. Лучшее одиночное упражнение для здоровья плеч и осанки.' },
  'front-raise': { sec: [], en: 'Front delts already get heavy work from every press — treat this as optional accessory volume, not a staple.', ru: 'Передние дельты и так получают нагрузку в каждом жиме — считайте это опциональной добавкой, а не основой.' },
  'upright-row': { sec: ['back', 'biceps'], en: 'Pulling the elbows high with a narrow grip forces shoulder impingement. If you do it at all, use a wide grip and stop below chest height.', ru: 'Высокий подъём локтей узким хватом провоцирует импинджмент плеча. Если делаете — широкий хват и остановка ниже уровня груди.' },

  /* ---------- Biceps ---------- */
  'bb-curl': { sec: ['forearms'], en: 'Elbows pinned to the sides, no swinging at the hips. An EZ bar is easier on the wrists than a straight bar.', ru: 'Локти прижаты к бокам, без раскачки в тазу. EZ-гриф щадит запястья сильнее прямого.' },
  'db-curl': { sec: ['forearms'], en: 'Supinate — rotate the palm up — as you lift; the biceps both bends the elbow and turns the forearm.', ru: 'Во время подъёма супинируйте кисть — разворачивайте ладонь вверх; бицепс и сгибает локоть, и разворачивает предплечье.' },
  'hammer-curl': { sec: ['forearms'], en: 'Neutral grip loads the brachialis and brachioradialis, which sit under and beside the biceps — this is what adds arm thickness.', ru: 'Нейтральный хват грузит брахиалис и брахиорадиалис, лежащие под бицепсом и рядом с ним, — именно они дают толщину руки.' },
  'incline-curl': { sec: ['forearms'], en: 'Lying back puts the biceps in a stretched position at the bottom, which is the hardest and most productive part of the range.', ru: 'Отклонение назад ставит бицепс в растянутое положение внизу — самая тяжёлая и самая продуктивная часть амплитуды.' },
  'preacher-curl': { sec: ['forearms'], en: 'The pad prevents any body English. Don\'t fully lock out at the bottom under a heavy load — it stresses the elbow tendon.', ru: 'Пюпитр исключает читинг корпусом. Не выпрямляйте руку полностью внизу с большим весом — это нагружает сухожилие локтя.' },
  'cable-curl': { sec: ['forearms'], en: 'Constant tension top to bottom. Good as the last biceps movement, where dumbbells start to feel weightless at the top.', ru: 'Постоянное натяжение сверху донизу. Хорош как завершающее упражнение на бицепс, где гантели в верхней точке уже почти невесомы.' },

  /* ---------- Triceps ---------- */
  'pushdown': { sec: [], en: 'Elbows locked at the sides, only the forearms move. Full extension at the bottom, controlled return.', ru: 'Локти зафиксированы у корпуса, движутся только предплечья. Внизу полное выпрямление, возврат подконтрольный.' },
  'rope-pushdown': { sec: [], en: 'Spread the rope apart at the bottom to finish the contraction. Slightly better lateral-head activation than a straight bar.', ru: 'Внизу разводите концы каната в стороны, завершая сокращение. Латеральный пучок включается чуть лучше, чем с прямой рукоятью.' },
  'oh-triceps': { sec: [], en: 'Overhead position stretches the long head, which the pushdown barely touches. Keep the elbows pointing forward, not flaring out.', ru: 'Положение над головой растягивает длинный пучок, который почти не работает в разгибаниях на блоке. Локти смотрят вперёд, не разъезжаются.' },
  'skullcrusher': { sec: [], en: 'Lower the bar behind the forehead, not to it, to keep tension on the triceps. Use an EZ bar and stop if the elbows complain.', ru: 'Опускайте гриф за голову, а не ко лбу, чтобы сохранить нагрузку на трицепс. Работайте с EZ-грифом и прекращайте, если локти дают о себе знать.' },
  'cg-bench': { sec: ['chest', 'shoulders'], en: 'Hands shoulder-width, elbows tucked, bar to the lower chest. Narrower than shoulder-width just wrecks the wrists without helping the triceps.', ru: 'Руки на ширине плеч, локти прижаты, гриф к низу груди. Уже плеч — только убивает запястья, не добавляя нагрузки на трицепс.' },
  'triceps-dip': { sec: ['chest', 'shoulders'], en: 'Torso upright — leaning forward turns it into a chest exercise. Stop at parallel to protect the shoulder.', ru: 'Корпус вертикально — наклон вперёд превращает движение в грудное. Останавливайтесь на параллели, чтобы беречь плечо.' },
  'bench-dip': { sec: ['shoulders'], en: 'Hands on the bench behind you, feet out front. Easy to load with a plate on the lap, but hard on the shoulder in the bottom position.', ru: 'Руки на скамье позади, ноги впереди. Легко нагрузить блином на бёдра, но нижняя точка тяжела для плеча.' },

  /* ---------- Quads ---------- */
  'leg-press': { sec: ['glutes', 'hamstrings'], en: 'Back and hips flat against the pad — this is what keeps the spine unloaded. Feet mid-platform, lower until the knees reach ~90°, never let the lower back round off the seat.', ru: 'Спина и таз плотно прижаты к спинке — именно это разгружает позвоночник. Стопы по центру платформы, опускайте до угла ~90° в колене, поясница не должна отрываться от сиденья.' },
  'hack-squat': { sec: ['glutes'], en: 'Back supported by the pad throughout, so the spine carries no free axial load. Feet mid-platform, descend under control, drive through the whole foot.', ru: 'Спина всё время на опоре, поэтому свободной осевой нагрузки на позвоночник нет. Стопы по центру платформы, опускайтесь подконтрольно, толкайтесь всей стопой.' },
  'machine-squat': { sec: ['glutes'], en: 'A squat pattern with the torso fixed — the safest way to train the movement when free-weight squats are off the table.', ru: 'Приседание с фиксированным корпусом — самый безопасный способ тренировать паттерн, когда свободные приседы противопоказаны.' },
  'back-squat': { sec: ['glutes', 'hamstrings', 'core'], en: 'The bar sits on the spine, so every kilo compresses it. Excellent lift in general, wrong lift when the back needs protecting.', ru: 'Штанга лежит на позвоночнике, и каждый килограмм сжимает его. Отличное упражнение в целом, но неподходящее, когда спину нужно беречь.' },
  'front-squat': { sec: ['glutes', 'core'], en: 'More upright than the back squat and more quad-dominant, but still a fully axial load on an unsupported spine.', ru: 'Корпус вертикальнее, чем в приседе со штангой на спине, акцент на квадрицепс сильнее, но осевая нагрузка на неподдержанный позвоночник остаётся.' },
  'goblet-squat': { sec: ['glutes', 'core'], en: 'Dumbbell held at the chest counterbalances you into an upright position. Light spinal load — a reasonable warm-up or low-load option.', ru: 'Гантель у груди работает противовесом и удерживает корпус вертикально. Осевая нагрузка невелика — подходит как разминка или лёгкий вариант.' },
  'leg-extension': { sec: [], en: 'Pure quad isolation with zero spinal load. Pause at the top; don\'t slam into full lockout with a heavy stack.', ru: 'Чистая изоляция квадрицепса без нагрузки на позвоночник. Пауза вверху; не выбрасывайте ногу в замок с большим весом.' },
  'bulgarian': { sec: ['glutes', 'hamstrings'], en: 'Rear foot elevated, front shin roughly vertical. Brutal for quads and glutes with far less spinal load than a barbell squat.', ru: 'Задняя нога на возвышении, голень передней ноги примерно вертикально. Жёстко нагружает квадрицепс и ягодицы при куда меньшей нагрузке на позвоночник, чем присед.' },
  'lunge': { sec: ['glutes', 'hamstrings'], en: 'Step out, drop the back knee towards the floor, push through the front heel. Dumbbells at the sides keep the load off the spine.', ru: 'Шаг вперёд, заднее колено опускается к полу, толчок через пятку передней ноги. Гантели по бокам не нагружают позвоночник.' },

  /* ---------- Hamstrings ---------- */
  'lying-leg-curl': { sec: ['calves'], en: 'Hips pressed into the pad; lifting them shortens the range and cheats the hamstrings. Control the negative — this is where the growth is.', ru: 'Таз прижат к подушке; если он отрывается, амплитуда укорачивается и бицепс бедра «обманывает». Контролируйте негативную фазу — рост именно там.' },
  'seated-leg-curl': { sec: ['calves'], en: 'The hip-flexed position stretches the hamstrings more than the lying version, and research favours it slightly for growth.', ru: 'Согнутое положение таза растягивает бицепс бедра сильнее, чем лёжа; данные говорят о небольшом преимуществе для роста.' },
  'db-rdl': { sec: ['glutes', 'back', 'forearms'], en: 'Hip hinge, not a squat: push the hips back with soft knees, dumbbells tracking the legs. Stop the moment the lower back starts to round — that\'s your range.', ru: 'Это шарнир в тазу, а не присед: таз уходит назад, колени мягкие, гантели скользят вдоль ног. Останавливайтесь в момент, когда поясница начинает круглиться — это ваша амплитуда.' },
  'bb-rdl': { sec: ['glutes', 'back', 'forearms'], en: 'Same pattern as the dumbbell version but the load sits further from the body, multiplying the shear force on the lower back.', ru: 'Тот же паттерн, что с гантелями, но вес дальше от тела, что увеличивает сдвиговую нагрузку на поясницу.' },
  'good-morning': { sec: ['glutes', 'back'], en: 'Bar on the back plus a deep hinge — one of the highest lower-back demands of any exercise. Very light or not at all.', ru: 'Штанга на спине плюс глубокий наклон — одна из самых высоких нагрузок на поясницу среди всех упражнений. Только очень лёгкий вес или совсем не делать.' },
  'nordic-curl': { sec: ['glutes'], en: 'Anchor the ankles, lower the torso as slowly as possible, catch yourself with the hands. Extremely effective and needs no equipment.', ru: 'Зафиксируйте стопы, опускайте корпус максимально медленно, страхуйте себя руками. Крайне эффективно и не требует оборудования.' },

  /* ---------- Glutes ---------- */
  'hip-thrust': { sec: ['hamstrings', 'core'], en: 'Upper back on a bench, bar across the hips with a pad. Drive the hips up, tuck the ribs down, squeeze at the top — no lower-back arch.', ru: 'Лопатки на скамье, штанга на бёдрах через подушку. Выталкивайте таз вверх, рёбра вниз, сжимайте ягодицы в верхней точке — без прогиба в пояснице.' },
  'hip-thrust-mach': { sec: ['hamstrings'], en: 'Same movement without balancing a bar on your hips. Easier to load progressively and easier on the setup.', ru: 'То же движение, но не нужно балансировать штангу на тазу. Проще прогрессировать в весе и проще устанавливаться.' },
  'kickback': { sec: ['hamstrings'], en: 'Isolation for one glute at a time. Keep the pelvis square — twisting to get more range defeats the point.', ru: 'Изоляция на одну ягодицу за раз. Держите таз ровно — разворот ради большей амплитуды убивает смысл упражнения.' },
  'hip-abduction': { sec: [], en: 'Targets the gluteus medius, which stabilises the pelvis when you walk and squat. Lean the torso slightly forward for more range.', ru: 'Нагружает среднюю ягодичную мышцу, которая стабилизирует таз при ходьбе и приседе. Небольшой наклон корпуса вперёд увеличивает амплитуду.' },

  /* ---------- Calves ---------- */
  'standing-calf': { sec: [], en: 'Straight knee targets the gastrocnemius. Full stretch at the bottom, full contraction at the top, no bouncing.', ru: 'Прямое колено нагружает икроножную мышцу. Полная растяжка внизу, полное сокращение вверху, без пружинистых движений.' },
  'seated-calf': { sec: [], en: 'Bent knee shifts the work to the soleus underneath — the one that adds calf width. Higher reps work well here.', ru: 'Согнутое колено переносит работу на камбаловидную мышцу под икроножной — именно она даёт ширину голени. Здесь хорошо работают высокие повторы.' },
  'leg-press-calf': { sec: [], en: 'Toes on the bottom edge of the platform, knees soft but not locked. Convenient to superset straight after leg press.', ru: 'Носки на нижнем крае платформы, колени мягкие, но не в замке. Удобно делать суперсетом сразу после жима ногами.' },

  /* ---------- Core ---------- */
  'plank': { sec: ['shoulders', 'glutes'], en: 'Forearms under the shoulders, ribs down, glutes squeezed, no sagging hips. If you can hold 90 seconds, add load rather than time.', ru: 'Предплечья под плечами, рёбра опущены, ягодицы напряжены, таз не проваливается. Если держите 90 секунд — добавляйте вес, а не время.' },
  'hanging-leg-raise': { sec: ['forearms'], en: 'Curl the pelvis up towards the ribs rather than just swinging the legs — that\'s what makes the abs work. Bend the knees to make it easier.', ru: 'Подкручивайте таз к рёбрам, а не просто закидывайте ноги — именно это включает пресс. Согнутые колени упрощают вариант.' },
  'cable-crunch': { sec: [], en: 'Kneel facing the stack, rope by the head, flex the spine to bring the elbows to the thighs. Hips stay still — it\'s a crunch, not a hinge.', ru: 'Встаньте на колени лицом к блоку, канат у головы, скручивайте позвоночник, приводя локти к бёдрам. Таз неподвижен — это скручивание, а не наклон.' },
  'woodchopper': { sec: ['shoulders', 'glutes'], en: 'Anti-rotation work for the obliques and deep core. Rotate through the torso with the arms straight, hips facing forward.', ru: 'Работа на косые и глубокие мышцы кора против ротации. Вращение идёт корпусом, руки прямые, таз смотрит вперёд.' },
  'ab-wheel': { sec: ['shoulders', 'back'], en: 'Roll out only as far as you can go without the lower back arching. Start from the knees; this is much harder than it looks.', ru: 'Выкатывайтесь ровно настолько, насколько можете, не прогибая поясницу. Начинайте с колен; упражнение намного сложнее, чем выглядит.' },
  'russian-twist': { sec: [], en: 'Lean back to about 45°, rotate the torso side to side. Slow and controlled beats fast and sloppy for the obliques.', ru: 'Отклонитесь назад примерно на 45°, поворачивайте корпус из стороны в сторону. Для косых медленно и подконтрольно лучше, чем быстро и небрежно.' },
  'dead-bug': { sec: [], en: 'Lower back pressed to the floor throughout while opposite arm and leg extend. Teaches the bracing pattern that protects the spine under load.', ru: 'Поясница всё время прижата к полу, разноимённые рука и нога выпрямляются. Обучает паттерну стабилизации, который защищает позвоночник под нагрузкой.' },
  'side-plank': { sec: ['shoulders', 'glutes'], en: 'Elbow under the shoulder, body in a straight line, hips lifted. Directly trains the lateral core that stabilises the lower back.', ru: 'Локоть под плечом, тело в прямой линии, таз поднят. Прямо тренирует боковой кор, стабилизирующий поясницу.' },

  /* ---------- Forearms ---------- */
  'wrist-curl': { sec: [], en: 'Forearms on the thighs or a bench, wrists hanging over the edge. High reps — the forearms respond to volume.', ru: 'Предплечья на бёдрах или скамье, кисти свисают за край. Высокие повторы — предплечья отзываются на объём.' },
  'farmers-carry': { sec: ['core', 'back', 'glutes'], en: 'Heavy dumbbells, walk tall with the ribs down and shoulders back. Builds grip, core stability and general work capacity at once.', ru: 'Тяжёлые гантели, идите с прямой спиной, рёбра опущены, плечи назад. Развивает хват, стабильность корпуса и общую выносливость сразу.' },

  /* ---------- Cardio ---------- */
  'treadmill': { sec: ['quads', 'calves'], en: 'Low-intensity walking, conversational pace. Keep it to ~15–20 min so it doesn\'t eat into the calorie surplus you need to gain.', ru: 'Ходьба низкой интенсивности, темп, при котором можно разговаривать. Держите в пределах 15–20 минут, чтобы не съедать профицит калорий, нужный для набора.' },
  'bike': { sec: ['quads', 'hamstrings'], en: 'Easy cycling is the least intrusive cardio for a gaining phase — no impact, low calorie cost, no interference with leg training.', ru: 'Спокойный велотренажёр — наименее конфликтное кардио в фазе набора: без ударной нагрузки, малый расход калорий, не мешает тренировке ног.' },
  'rowing': { sec: ['back', 'quads', 'biceps'], en: 'Full-body and fairly demanding. Drive with the legs first, then lean back, then pull — arms last, not first.', ru: 'Задействует всё тело и довольно требователен. Сначала толчок ногами, затем отклонение корпуса, затем тяга руками — руки в последнюю очередь.' },
  'elliptical': { sec: ['quads', 'glutes'], en: 'Zero impact, easy on the joints and the lower back. A good default when the knees or spine don\'t want running.', ru: 'Нулевая ударная нагрузка, щадит суставы и поясницу. Хороший вариант по умолчанию, когда колени или спина против бега.' },
  'stair-climber': { sec: ['glutes', 'quads', 'calves'], en: 'Higher calorie burn than walking — use sparingly during a gaining phase. Stand tall, don\'t lean on the handles.', ru: 'Сжигает больше калорий, чем ходьба, — в фазе набора используйте умеренно. Стойте прямо, не наваливайтесь на поручни.' },
};
